// 단어 데이터베이스: 토익 중상급 & 비즈니스 영어 중상급 수준
// 매일 20개씩 순환하며 학습합니다.
// 각 항목: en(영단어), ipa(발음), pos(품사), ko(뜻), ex(예문)
const WORD_BANK = [
  { en: "accomplish", ipa: "/əˈkɑːmplɪʃ/", pos: "v.", ko: "완수하다, 성취하다", ex: "She accomplished all her tasks before the deadline." },
  { en: "accountable", ipa: "/əˈkaʊntəbl/", pos: "adj.", ko: "책임이 있는", ex: "Managers are accountable for their team's performance." },
  { en: "acquire", ipa: "/əˈkwaɪər/", pos: "v.", ko: "인수하다, 획득하다", ex: "The company acquired a smaller competitor last year." },
  { en: "agenda", ipa: "/əˈdʒendə/", pos: "n.", ko: "안건, 의제", ex: "Let's go over today's agenda first." },
  { en: "allocate", ipa: "/ˈæləkeɪt/", pos: "v.", ko: "할당하다", ex: "We need to allocate more funds to marketing." },
  { en: "amendment", ipa: "/əˈmendmənt/", pos: "n.", ko: "수정, 개정", ex: "The contract requires a small amendment." },
  { en: "anticipate", ipa: "/ænˈtɪsɪpeɪt/", pos: "v.", ko: "예상하다", ex: "We anticipate a rise in demand next quarter." },
  { en: "applicant", ipa: "/ˈæplɪkənt/", pos: "n.", ko: "지원자", ex: "We received over 100 applicants for the position." },
  { en: "appraisal", ipa: "/əˈpreɪzəl/", pos: "n.", ko: "(성과) 평가", ex: "Her annual appraisal was very positive." },
  { en: "approve", ipa: "/əˈpruːv/", pos: "v.", ko: "승인하다", ex: "The board approved the new budget." },
  { en: "arrange", ipa: "/əˈreɪndʒ/", pos: "v.", ko: "준비하다, 마련하다", ex: "I'll arrange a meeting for next week." },
  { en: "asset", ipa: "/ˈæset/", pos: "n.", ko: "자산", ex: "Skilled employees are the company's greatest asset." },
  { en: "attain", ipa: "/əˈteɪn/", pos: "v.", ko: "달성하다", ex: "The team attained its sales target early." },
  { en: "audit", ipa: "/ˈɔːdɪt/", pos: "n./v.", ko: "감사(하다)", ex: "The firm conducts an audit every year." },
  { en: "authorize", ipa: "/ˈɔːθəraɪz/", pos: "v.", ko: "승인하다, 권한을 주다", ex: "Only the director can authorize this expense." },
  { en: "bankrupt", ipa: "/ˈbæŋkrʌpt/", pos: "adj.", ko: "파산한", ex: "The store went bankrupt after two bad years." },
  { en: "benchmark", ipa: "/ˈbentʃmɑːrk/", pos: "n.", ko: "기준, 척도", ex: "We use last year's sales as a benchmark." },
  { en: "bid", ipa: "/bɪd/", pos: "n./v.", ko: "입찰(하다)", ex: "Three companies submitted a bid for the project." },
  { en: "brochure", ipa: "/broʊˈʃʊr/", pos: "n.", ko: "안내 책자", ex: "Please read the product brochure carefully." },
  { en: "budget", ipa: "/ˈbʌdʒɪt/", pos: "n.", ko: "예산", ex: "We need to stay within budget this quarter." },
  { en: "candidate", ipa: "/ˈkændɪdeɪt/", pos: "n.", ko: "후보자", ex: "She's the strongest candidate for the job." },
  { en: "clause", ipa: "/klɔːz/", pos: "n.", ko: "(계약서 등의) 조항", ex: "Read the cancellation clause carefully." },
  { en: "client", ipa: "/ˈklaɪənt/", pos: "n.", ko: "고객", ex: "We have a call with a client at noon." },
  { en: "collaborate", ipa: "/kəˈlæbəreɪt/", pos: "v.", ko: "협력하다", ex: "Our teams collaborated on the new product." },
  { en: "commission", ipa: "/kəˈmɪʃən/", pos: "n.", ko: "수수료, 커미션", ex: "Sales staff earn a commission on each sale." },
  { en: "commute", ipa: "/kəˈmjuːt/", pos: "v./n.", ko: "통근(하다)", ex: "He commutes to work by train." },
  { en: "compensation", ipa: "/ˌkɑːmpənˈseɪʃən/", pos: "n.", ko: "보상, 급여", ex: "The compensation package includes health insurance." },
  { en: "competitive", ipa: "/kəmˈpetətɪv/", pos: "adj.", ko: "경쟁력 있는", ex: "We offer competitive prices in the market." },
  { en: "compliance", ipa: "/kəmˈplaɪəns/", pos: "n.", ko: "준수", ex: "The audit checks for compliance with regulations." },
  { en: "comprise", ipa: "/kəmˈpraɪz/", pos: "v.", ko: "구성하다", ex: "The committee comprises five members." },
  { en: "confidential", ipa: "/ˌkɑːnfɪˈdenʃəl/", pos: "adj.", ko: "기밀의", ex: "This document is strictly confidential." },
  { en: "consecutive", ipa: "/kənˈsekjətɪv/", pos: "adj.", ko: "연속적인", ex: "Profits rose for the third consecutive year." },
  { en: "consolidate", ipa: "/kənˈsɑːlɪdeɪt/", pos: "v.", ko: "통합하다", ex: "The two branches will consolidate next month." },
  { en: "contract", ipa: "/ˈkɑːntrækt/", pos: "n.", ko: "계약(서)", ex: "Please sign the contract by Friday." },
  { en: "correspondence", ipa: "/ˌkɔːrəˈspɑːndəns/", pos: "n.", ko: "서신, 왕래", ex: "All correspondence should go through email." },
  { en: "cost-effective", ipa: "/ˌkɔːst ɪˈfektɪv/", pos: "adj.", ko: "비용 효율적인", ex: "This method is more cost-effective." },
  { en: "credential", ipa: "/krɪˈdenʃəl/", pos: "n.", ko: "자격 (증명)", ex: "Please submit your credentials with the application." },
  { en: "deadline", ipa: "/ˈdedlaɪn/", pos: "n.", ko: "마감 기한", ex: "The deadline for the report is Monday." },
  { en: "deduct", ipa: "/dɪˈdʌkt/", pos: "v.", ko: "공제하다", ex: "Taxes are deducted from your salary." },
  { en: "delegate", ipa: "/ˈdelɪɡeɪt/", pos: "v./n.", ko: "위임하다, 대표", ex: "A good manager knows how to delegate tasks." },
  { en: "deliverable", ipa: "/dɪˈlɪvərəbl/", pos: "n.", ko: "(프로젝트) 결과물", ex: "The first deliverable is due next week." },
  { en: "depreciate", ipa: "/dɪˈpriːʃieɪt/", pos: "v.", ko: "가치가 하락하다", ex: "New cars depreciate quickly." },
  { en: "designate", ipa: "/ˈdezɪɡneɪt/", pos: "v.", ko: "지정하다", ex: "She was designated as team leader." },
  { en: "discrepancy", ipa: "/dɪˈskrepənsi/", pos: "n.", ko: "불일치, 차이", ex: "There's a discrepancy in the invoice." },
  { en: "dispatch", ipa: "/dɪˈspætʃ/", pos: "v.", ko: "발송하다", ex: "The order will be dispatched today." },
  { en: "distribute", ipa: "/dɪˈstrɪbjuːt/", pos: "v.", ko: "배포하다, 유통하다", ex: "We distribute products across Asia." },
  { en: "diversify", ipa: "/daɪˈvɜːrsɪfaɪ/", pos: "v.", ko: "다각화하다", ex: "The company plans to diversify its products." },
  { en: "downsize", ipa: "/ˈdaʊnsaɪz/", pos: "v.", ko: "(인력을) 축소하다", ex: "The firm decided to downsize its staff." },
  { en: "draft", ipa: "/dræft/", pos: "n./v.", ko: "초안(을 작성하다)", ex: "Can you draft the email for me?" },
  { en: "eligible", ipa: "/ˈelɪdʒəbl/", pos: "adj.", ko: "자격이 있는", ex: "Full-time staff are eligible for benefits." },
  { en: "endorse", ipa: "/ɪnˈdɔːrs/", pos: "v.", ko: "지지하다, 보증하다", ex: "The CEO endorsed the new strategy." },
  { en: "enterprise", ipa: "/ˈentərpraɪz/", pos: "n.", ko: "기업", ex: "It's a small but growing enterprise." },
  { en: "entrepreneur", ipa: "/ˌɑːntrəprəˈnɜːr/", pos: "n.", ko: "사업가", ex: "She became a successful entrepreneur." },
  { en: "equity", ipa: "/ˈekwəti/", pos: "n.", ko: "지분, 자기자본", ex: "Investors received equity in the startup." },
  { en: "estimate", ipa: "/ˈestɪmeɪt/", pos: "v./n.", ko: "견적(내다), 추정하다", ex: "Can you send me an estimate first?" },
  { en: "expenditure", ipa: "/ɪkˈspendɪtʃər/", pos: "n.", ko: "지출", ex: "Government expenditure increased this year." },
  { en: "facilitate", ipa: "/fəˈsɪlɪteɪt/", pos: "v.", ko: "촉진하다, 원활하게 하다", ex: "The software facilitates team communication." },
  { en: "feasible", ipa: "/ˈfiːzəbl/", pos: "adj.", ko: "실현 가능한", ex: "Is the new plan financially feasible?" },
  { en: "finalize", ipa: "/ˈfaɪnəlaɪz/", pos: "v.", ko: "마무리 짓다", ex: "We need to finalize the contract today." },
  { en: "fiscal", ipa: "/ˈfɪskəl/", pos: "adj.", ko: "회계의, 재정의", ex: "Our fiscal year ends in December." },
  { en: "forecast", ipa: "/ˈfɔːrkæst/", pos: "n./v.", ko: "예측(하다)", ex: "The sales forecast looks promising." },
  { en: "fraud", ipa: "/frɔːd/", pos: "n.", ko: "사기", ex: "The company was accused of fraud." },
  { en: "gross", ipa: "/ɡroʊs/", pos: "adj.", ko: "총(액)의", ex: "Gross revenue rose by 10 percent." },
  { en: "hierarchy", ipa: "/ˈhaɪərɑːrki/", pos: "n.", ko: "위계, 서열", ex: "The company has a flat hierarchy." },
  { en: "implement", ipa: "/ˈɪmplɪment/", pos: "v.", ko: "시행하다", ex: "We will implement the new policy soon." },
  { en: "incentive", ipa: "/ɪnˈsentɪv/", pos: "n.", ko: "장려책, 인센티브", ex: "The bonus is a great incentive." },
  { en: "incur", ipa: "/ɪnˈkɜːr/", pos: "v.", ko: "(비용 등을) 발생시키다", ex: "Late payments incur extra fees." },
  { en: "inflation", ipa: "/ɪnˈfleɪʃən/", pos: "n.", ko: "물가 상승, 인플레이션", ex: "Inflation affects everyone's spending." },
  { en: "infrastructure", ipa: "/ˈɪnfrəstrʌktʃər/", pos: "n.", ko: "사회 기반 시설", ex: "The city invested in new infrastructure." },
  { en: "initiative", ipa: "/ɪˈnɪʃətɪv/", pos: "n.", ko: "계획, 주도권", ex: "She launched a new sustainability initiative." },
  { en: "installment", ipa: "/ɪnˈstɔːlmənt/", pos: "n.", ko: "할부, 분할 납입", ex: "You can pay in monthly installments." },
  { en: "invoice", ipa: "/ˈɪnvɔɪs/", pos: "n.", ko: "청구서, 송장", ex: "Please send the invoice to accounting." },
  { en: "itinerary", ipa: "/aɪˈtɪnəreri/", pos: "n.", ko: "여행 일정", ex: "Here's your business trip itinerary." },
  { en: "jeopardize", ipa: "/ˈdʒepərdaɪz/", pos: "v.", ko: "위태롭게 하다", ex: "The delay could jeopardize the deal." },
  { en: "joint venture", ipa: "/dʒɔɪnt ˈventʃər/", pos: "n.", ko: "합작 투자", ex: "They formed a joint venture overseas." },
  { en: "layoff", ipa: "/ˈleɪɔːf/", pos: "n.", ko: "정리해고", ex: "The company announced layoffs last week." },
  { en: "lease", ipa: "/liːs/", pos: "n./v.", ko: "임대(하다)", ex: "We lease office space downtown." },
  { en: "legislation", ipa: "/ˌledʒɪsˈleɪʃən/", pos: "n.", ko: "법률, 입법", ex: "New legislation affects small businesses." },
  { en: "leverage", ipa: "/ˈlevərɪdʒ/", pos: "v./n.", ko: "활용하다, 지렛대", ex: "We should leverage our online presence." },
  { en: "liability", ipa: "/ˌlaɪəˈbɪləti/", pos: "n.", ko: "책임, 부채", ex: "The company has limited liability." },
  { en: "logistics", ipa: "/ləˈdʒɪstɪks/", pos: "n.", ko: "물류", ex: "Logistics costs rose due to fuel prices." },
  { en: "margin", ipa: "/ˈmɑːrdʒɪn/", pos: "n.", ko: "이윤, 마진", ex: "The profit margin is quite low." },
  { en: "merger", ipa: "/ˈmɜːrdʒər/", pos: "n.", ko: "합병", ex: "The merger created a huge company." },
  { en: "milestone", ipa: "/ˈmaɪlstoʊn/", pos: "n.", ko: "중요한 단계, 이정표", ex: "Launching the app was a big milestone." },
  { en: "mitigate", ipa: "/ˈmɪtɪɡeɪt/", pos: "v.", ko: "완화하다", ex: "We took steps to mitigate the risk." },
  { en: "negotiate", ipa: "/nɪˈɡoʊʃieɪt/", pos: "v.", ko: "협상하다", ex: "They negotiated a lower price." },
  { en: "net", ipa: "/net/", pos: "adj.", ko: "순(純)의", ex: "Net income increased this quarter." },
  { en: "niche", ipa: "/nɪtʃ/", pos: "n.", ko: "틈새시장", ex: "The startup found a profitable niche." },
  { en: "nominate", ipa: "/ˈnɑːmɪneɪt/", pos: "v.", ko: "지명하다, 추천하다", ex: "She was nominated for the award." },
  { en: "obsolete", ipa: "/ˌɑːbsəˈliːt/", pos: "adj.", ko: "구식의, 쓸모없는", ex: "The old software is now obsolete." },
  { en: "outsource", ipa: "/ˈaʊtsɔːrs/", pos: "v.", ko: "외주를 주다", ex: "We outsource our customer support." },
  { en: "overhead", ipa: "/ˈoʊvərhed/", pos: "n.", ko: "간접비, 운영비", ex: "We need to reduce overhead costs." },
  { en: "oversee", ipa: "/ˌoʊvərˈsiː/", pos: "v.", ko: "감독하다", ex: "She oversees the entire production line." },
  { en: "partnership", ipa: "/ˈpɑːrtnərʃɪp/", pos: "n.", ko: "동업, 제휴", ex: "The two firms formed a partnership." },
  { en: "payroll", ipa: "/ˈpeɪroʊl/", pos: "n.", ko: "급여 명부, 급여", ex: "The payroll is processed monthly." },
  { en: "pending", ipa: "/ˈpendɪŋ/", pos: "adj.", ko: "미결의, 보류 중인", ex: "The approval is still pending." },
  { en: "portfolio", ipa: "/pɔːrtˈfoʊlioʊ/", pos: "n.", ko: "포트폴리오", ex: "She manages a large stock portfolio." },
  { en: "premises", ipa: "/ˈpremɪsɪz/", pos: "n.", ko: "부지, 구내", ex: "Visitors must sign in at the premises." },
  { en: "procurement", ipa: "/prəˈkjʊrmənt/", pos: "n.", ko: "조달, 구매", ex: "The procurement team ordered new laptops." },
  { en: "productivity", ipa: "/ˌproʊdʌkˈtɪvəti/", pos: "n.", ko: "생산성", ex: "The new tool boosted productivity." },
  { en: "proficient", ipa: "/prəˈfɪʃənt/", pos: "adj.", ko: "능숙한", ex: "She is proficient in three languages." },
  { en: "projection", ipa: "/prəˈdʒekʃən/", pos: "n.", ko: "예상, 추정", ex: "Our sales projection looks strong." },
  { en: "proposal", ipa: "/prəˈpoʊzəl/", pos: "n.", ko: "제안(서)", ex: "Please review the proposal by Friday." },
  { en: "prospective", ipa: "/prəˈspektɪv/", pos: "adj.", ko: "장래의, 유망한", ex: "We contacted several prospective clients." },
  { en: "provision", ipa: "/prəˈvɪʒən/", pos: "n.", ko: "조항, 대비", ex: "The contract includes a cancellation provision." },
  { en: "quarterly", ipa: "/ˈkwɔːrtərli/", pos: "adj./adv.", ko: "분기별의", ex: "We hold quarterly reviews." },
  { en: "quota", ipa: "/ˈkwoʊtə/", pos: "n.", ko: "할당량", ex: "He exceeded his sales quota this month." },
  { en: "rebate", ipa: "/ˈriːbeɪt/", pos: "n.", ko: "환급금", ex: "You can get a rebate on this purchase." },
  { en: "recession", ipa: "/rɪˈseʃən/", pos: "n.", ko: "경기 침체", ex: "The country entered a recession." },
  { en: "recruit", ipa: "/rɪˈkruːt/", pos: "v.", ko: "채용하다", ex: "We're recruiting new sales staff." },
  { en: "redundant", ipa: "/rɪˈdʌndənt/", pos: "adj.", ko: "정리해고된, 불필요한", ex: "Fifty workers were made redundant." },
  { en: "reimburse", ipa: "/ˌriːɪmˈbɜːrs/", pos: "v.", ko: "환급하다, 상환하다", ex: "The company will reimburse your travel costs." },
  { en: "relocate", ipa: "/riːˈloʊkeɪt/", pos: "v.", ko: "이전하다", ex: "The office will relocate next year." },
  { en: "remuneration", ipa: "/rɪˌmjuːnəˈreɪʃən/", pos: "n.", ko: "보수, 급여", ex: "The remuneration package is generous." },
  { en: "renew", ipa: "/rɪˈnuː/", pos: "v.", ko: "갱신하다", ex: "We need to renew the lease soon." },
  { en: "resign", ipa: "/rɪˈzaɪn/", pos: "v.", ko: "사임하다", ex: "She resigned from her position." },
  { en: "resolve", ipa: "/rɪˈzɑːlv/", pos: "v.", ko: "해결하다", ex: "We resolved the issue quickly." },
  { en: "resource", ipa: "/ˈriːsɔːrs/", pos: "n.", ko: "자원", ex: "We lack the resources for this project." },
  { en: "retail", ipa: "/ˈriːteɪl/", pos: "n./adj.", ko: "소매(의)", ex: "The retail price is quite high." },
  { en: "revenue", ipa: "/ˈrevənuː/", pos: "n.", ko: "수익, 매출", ex: "Revenue grew by fifteen percent." },
  { en: "reward", ipa: "/rɪˈwɔːrd/", pos: "n./v.", ko: "보상(하다)", ex: "Employees are rewarded for good performance." },
  { en: "royalty", ipa: "/ˈrɔɪəlti/", pos: "n.", ko: "로열티, 저작권료", ex: "The author receives a royalty on each book." },
  { en: "sales pitch", ipa: "/seɪlz pɪtʃ/", pos: "n.", ko: "영업 설명", ex: "He gave a convincing sales pitch." },
  { en: "sanction", ipa: "/ˈsæŋkʃən/", pos: "n./v.", ko: "제재(하다)", ex: "The country faced trade sanctions." },
  { en: "scope", ipa: "/skoʊp/", pos: "n.", ko: "범위", ex: "This is beyond the scope of the project." },
  { en: "sector", ipa: "/ˈsektər/", pos: "n.", ko: "부문, 분야", ex: "The tech sector is growing fast." },
  { en: "shareholder", ipa: "/ˈʃerhoʊldər/", pos: "n.", ko: "주주", ex: "Shareholders approved the merger." },
  { en: "shipment", ipa: "/ˈʃɪpmənt/", pos: "n.", ko: "수송(품), 선적", ex: "The shipment arrived a day late." },
  { en: "simultaneously", ipa: "/ˌsaɪmlˈteɪniəsli/", pos: "adv.", ko: "동시에", ex: "The two events happened simultaneously." },
  { en: "specification", ipa: "/ˌspesɪfɪˈkeɪʃən/", pos: "n.", ko: "사양, 명세", ex: "The product meets all specifications." },
  { en: "sponsor", ipa: "/ˈspɑːnsər/", pos: "n./v.", ko: "후원(하다)", ex: "The event is sponsored by a bank." },
  { en: "stakeholder", ipa: "/ˈsteɪkhoʊldər/", pos: "n.", ko: "이해관계자", ex: "All stakeholders were invited to the meeting." },
  { en: "streamline", ipa: "/ˈstriːmlaɪn/", pos: "v.", ko: "간소화하다", ex: "The new system streamlines the workflow." },
  { en: "subsidiary", ipa: "/səbˈsɪdieri/", pos: "n.", ko: "자회사", ex: "The company has a subsidiary in Korea." },
  { en: "subsidy", ipa: "/ˈsʌbsɪdi/", pos: "n.", ko: "보조금", ex: "Farmers receive a government subsidy." },
  { en: "surplus", ipa: "/ˈsɜːrpləs/", pos: "n.", ko: "흑자, 잉여", ex: "The company reported a trade surplus." },
  { en: "suspend", ipa: "/səˈspend/", pos: "v.", ko: "정지하다, 중단하다", ex: "The service was temporarily suspended." },
  { en: "sustainable", ipa: "/səˈsteɪnəbl/", pos: "adj.", ko: "지속 가능한", ex: "We aim for sustainable growth." },
  { en: "tariff", ipa: "/ˈtærɪf/", pos: "n.", ko: "관세", ex: "New tariffs raised import prices." },
  { en: "tenant", ipa: "/ˈtenənt/", pos: "n.", ko: "세입자", ex: "The tenant signed a two-year lease." },
  { en: "terminate", ipa: "/ˈtɜːrmɪneɪt/", pos: "v.", ko: "종료하다, 해지하다", ex: "The contract can be terminated early." },
  { en: "transaction", ipa: "/trænˈzækʃən/", pos: "n.", ko: "거래", ex: "The bank processes thousands of transactions daily." },
  { en: "turnover", ipa: "/ˈtɜːrnoʊvər/", pos: "n.", ko: "매출액, 이직률", ex: "Staff turnover has decreased this year." },
  { en: "undertake", ipa: "/ˌʌndərˈteɪk/", pos: "v.", ko: "착수하다, 맡다", ex: "The firm will undertake the new project." },
  { en: "unveil", ipa: "/ʌnˈveɪl/", pos: "v.", ko: "공개하다, 발표하다", ex: "The company unveiled its new logo." },
  { en: "utilize", ipa: "/ˈjuːtəlaɪz/", pos: "v.", ko: "활용하다", ex: "We should utilize all available resources." },
  { en: "valid", ipa: "/ˈvælɪd/", pos: "adj.", ko: "유효한", ex: "This coupon is valid until Friday." },
  { en: "venture", ipa: "/ˈventʃər/", pos: "n.", ko: "사업, 벤처", ex: "It's a risky business venture." },
  { en: "viable", ipa: "/ˈvaɪəbl/", pos: "adj.", ko: "실행 가능한", ex: "Is this a financially viable plan?" },
  { en: "warranty", ipa: "/ˈwɔːrənti/", pos: "n.", ko: "품질 보증(서)", ex: "The laptop comes with a two-year warranty." },
  { en: "workforce", ipa: "/ˈwɜːrkfɔːrs/", pos: "n.", ko: "노동 인구, 인력", ex: "The workforce has grown significantly." },
  { en: "yield", ipa: "/jiːld/", pos: "n./v.", ko: "수익(을 내다)", ex: "The bond offers a high yield." },
  { en: "accommodate", ipa: "/əˈkɑːmədeɪt/", pos: "v.", ko: "수용하다", ex: "The hotel can accommodate 200 guests." },
  { en: "advocate", ipa: "/ˈædvəkeɪt/", pos: "v./n.", ko: "옹호하다, 지지자", ex: "She advocates for flexible working hours." },
  { en: "affiliate", ipa: "/əˈfɪlieɪt/", pos: "n./v.", ko: "계열사, 제휴하다", ex: "The store is an affiliate of a larger chain." },
  { en: "ambiguous", ipa: "/æmˈbɪɡjuəs/", pos: "adj.", ko: "애매한", ex: "The instructions were a bit ambiguous." },
  { en: "amortize", ipa: "/ˈæmərtaɪz/", pos: "v.", ko: "분할 상환하다", ex: "The loan is amortized over ten years." },
  { en: "appraise", ipa: "/əˈpreɪz/", pos: "v.", ko: "평가하다", ex: "An expert appraised the property's value." },
  { en: "arbitration", ipa: "/ˌɑːrbɪˈtreɪʃən/", pos: "n.", ko: "중재", ex: "The dispute went to arbitration." },
  { en: "assess", ipa: "/əˈses/", pos: "v.", ko: "평가하다", ex: "We need to assess the risks first." },
  { en: "attrition", ipa: "/əˈtrɪʃən/", pos: "n.", ko: "(직원) 이직, 감소", ex: "The company suffers high employee attrition." },
  { en: "autonomy", ipa: "/ɔːˈtɑːnəmi/", pos: "n.", ko: "자율성", ex: "Employees value autonomy in their work." },
  { en: "beneficiary", ipa: "/ˌbenɪˈfɪʃieri/", pos: "n.", ko: "수혜자", ex: "She is the beneficiary of the policy." },
  { en: "capital", ipa: "/ˈkæpɪtl/", pos: "n.", ko: "자본", ex: "The startup needs more capital to grow." },
  { en: "clientele", ipa: "/ˌklaɪənˈtel/", pos: "n.", ko: "(전체) 고객층", ex: "The restaurant has a loyal clientele." },
  { en: "collateral", ipa: "/kəˈlætərəl/", pos: "n.", ko: "담보", ex: "The bank required collateral for the loan." },
  { en: "commodity", ipa: "/kəˈmɑːdəti/", pos: "n.", ko: "상품, 원자재", ex: "Oil is a globally traded commodity." },
  { en: "conglomerate", ipa: "/kənˈɡlɑːmərət/", pos: "n.", ko: "복합 기업", ex: "The brand is owned by a large conglomerate." },
  { en: "consensus", ipa: "/kənˈsensəs/", pos: "n.", ko: "합의", ex: "The team reached a consensus quickly." },
  { en: "constituent", ipa: "/kənˈstɪtʃuənt/", pos: "n.", ko: "구성 요소, 유권자", ex: "Plastic is a key constituent of the product." },
  { en: "contingency", ipa: "/kənˈtɪndʒənsi/", pos: "n.", ko: "만일의 사태, 대비책", ex: "We need a contingency plan." },
  { en: "counterpart", ipa: "/ˈkaʊntərpɑːrt/", pos: "n.", ko: "상대방", ex: "She met her counterpart from the other firm." },
  { en: "curb", ipa: "/kɜːrb/", pos: "v.", ko: "억제하다", ex: "The policy aims to curb spending." },
  { en: "decline", ipa: "/dɪˈklaɪn/", pos: "v./n.", ko: "감소(하다), 거절하다", ex: "Sales declined during the recession." },
  { en: "default", ipa: "/dɪˈfɔːlt/", pos: "n./v.", ko: "채무 불이행", ex: "The company defaulted on its loan." },
  { en: "deficit", ipa: "/ˈdefɪsɪt/", pos: "n.", ko: "적자", ex: "The budget deficit grew last year." },
  { en: "depreciation", ipa: "/dɪˌpriːʃiˈeɪʃən/", pos: "n.", ko: "감가상각", ex: "Depreciation is calculated annually." },
  { en: "disburse", ipa: "/dɪsˈbɜːrs/", pos: "v.", ko: "지불하다, 지급하다", ex: "Funds will be disbursed next week." },
  { en: "dividend", ipa: "/ˈdɪvɪdend/", pos: "n.", ko: "배당금", ex: "Shareholders received a dividend this year." },
  { en: "embezzle", ipa: "/ɪmˈbezl/", pos: "v.", ko: "횡령하다", ex: "He was accused of embezzling funds." },
  { en: "endorsement", ipa: "/ɪnˈdɔːrsmənt/", pos: "n.", ko: "지지, 보증", ex: "The product got a celebrity endorsement." },
  { en: "entity", ipa: "/ˈentəti/", pos: "n.", ko: "실체, 법인", ex: "The subsidiary is a separate legal entity." },
  { en: "escrow", ipa: "/ˈeskroʊ/", pos: "n.", ko: "에스크로, 위탁 계약금", ex: "The deposit is held in escrow." },
  { en: "exempt", ipa: "/ɪɡˈzempt/", pos: "adj./v.", ko: "면제된, 면제하다", ex: "Non-profits are exempt from this tax." },
  { en: "expedite", ipa: "/ˈekspədaɪt/", pos: "v.", ko: "신속히 처리하다", ex: "Please expedite this shipment." },
  { en: "franchise", ipa: "/ˈfræntʃaɪz/", pos: "n.", ko: "가맹점, 프랜차이즈", ex: "She owns a coffee shop franchise." },
  { en: "groundwork", ipa: "/ˈɡraʊndwɜːrk/", pos: "n.", ko: "기초 작업", ex: "We laid the groundwork for the deal." },
  { en: "headquarters", ipa: "/ˈhedkwɔːrtərz/", pos: "n.", ko: "본사", ex: "The headquarters is located in Seoul." },
  { en: "inventory", ipa: "/ˈɪnvəntɔːri/", pos: "n.", ko: "재고", ex: "We need to check the inventory levels." },
  { en: "lucrative", ipa: "/ˈluːkrətɪv/", pos: "adj.", ko: "수익성이 좋은", ex: "It's a highly lucrative business." },
  { en: "mandate", ipa: "/ˈmændeɪt/", pos: "n./v.", ko: "지시하다, 위임", ex: "The new law mandates safety training." },
  { en: "monopoly", ipa: "/məˈnɑːpəli/", pos: "n.", ko: "독점", ex: "The firm holds a monopoly in the region." },
  { en: "obligation", ipa: "/ˌɑːblɪˈɡeɪʃən/", pos: "n.", ko: "의무", ex: "We have a legal obligation to comply." },
  { en: "overdue", ipa: "/ˌoʊvərˈduː/", pos: "adj.", ko: "기한이 지난, 연체된", ex: "The invoice is now two weeks overdue." },
  { en: "petty cash", ipa: "/ˈpeti kæʃ/", pos: "n.", ko: "소액 현금", ex: "Use petty cash for small office expenses." },
  { en: "proceeds", ipa: "/ˈproʊsiːdz/", pos: "n.", ko: "수익금", ex: "All proceeds go to charity." },
  { en: "quorum", ipa: "/ˈkwɔːrəm/", pos: "n.", ko: "정족수", ex: "We don't have a quorum for the vote." },
];

if (typeof module !== "undefined") {
  module.exports = WORD_BANK;
}
