// 단어 데이터베이스: 토익 중상급 & 비즈니스 영어 중상급 수준
// 매일 20개씩 순환하며 학습합니다.
// 각 항목: en(영단어), ipa(발음), pos(품사), ko(뜻), ex(예문)
const WORD_BANK = [
  { en: "accomplish", ipa: "/əˈkɑːmplɪʃ/", pos: "v.", ko: "완수하다, 성취하다", ex: "She accomplished all her tasks before the deadline." },
  { en: "accountable", ipa: "/əˈkaʊntəbl/", pos: "adj.", ko: "책임이 있는", ex: "Managers are accountable for their team's performance." },
  { en: "acquire", ipa: "/əˈkwaɪər/", pos: "v.", ko: "인수하다, 획득하다", ex: "The company acquired a smaller competitor last year." },
  { en: "agenda", ipa: "/əˈdʒendə/", pos: "n.", ko: "안건, 의제", ex: "Let's go over today's agenda first." },
  { en: "allocate", ipa: "/ˈæləkeɪt/", pos: "v.", ko: "할당하다", ex: "We need to allocate more funds to marketing." },
  { en: "amendment", ipa: "/əˈmendmənt/", pos: "n.", ko: "수정, 개정", ex: "The contract requires a small amendment." },
  { en: "anticipate", ipa: "/ænˈtɪsɪpeɪt/", pos: "v.", ko: "예상하다", ex: "We anticipate a rise in demand next quarter." },
  { en: "applicant", ipa: "/ˈæplɪkənt/", pos: "n.", ko: "지원자", ex: "We received over 100 applicants for the position." },
  { en: "appraisal", ipa: "/əˈpreɪzəl/", pos: "n.", ko: "(성과) 평가", ex: "Her annual appraisal was very positive." },
  { en: "approve", ipa: "/əˈpruːv/", pos: "v.", ko: "승인하다", ex: "The board approved the new budget." },
  { en: "arrange", ipa: "/əˈreɪndʒ/", pos: "v.", ko: "준비하다, 마련하다", ex: "I'll arrange a meeting for next week." },
  { en: "asset", ipa: "/ˈæset/", pos: "n.", ko: "자산", ex: "Skilled employees are the company's greatest asset." },
  { en: "attain", ipa: "/əˈteɪn/", pos: "v.", ko: "달성하다", ex: "The team attained its sales target early." },
  { en: "audit", ipa: "/ˈɔːdɪt/", pos: "n./v.", ko: "감사(하다)", ex: "The firm conducts an audit every year." },
  { en: "authorize", ipa: "/ˈɔːθəraɪz/", pos: "v.", ko: "승인하다, 권한을 주다", ex: "Only the director can authorize this expense." },
  { en: "bankrupt", ipa: "/ˈbæŋkrʌpt/", pos: "adj.", ko: "파산한", ex: "The store went bankrupt after two bad years." },
  { en: "benchmark", ipa: "/ˈbentʃmɑːrk/", pos: "n.", ko: "기준, 척도", ex: "We use last year's sales as a benchmark." },
  { en: "bid", ipa: "/bɪd/", pos: "n./v.", ko: "입찰(하다)", ex: "Three companies submitted a bid for the project." },
  { en: "brochure", ipa: "/broʊˈʃʊr/", pos: "n.", ko: "안내 책자", ex: "Please read the product brochure carefully." },
  { en: "budget", ipa: "/ˈbʌdʒɪt/", pos: "n.", ko: "예산", ex: "We need to stay within budget this quarter." },
  { en: "candidate", ipa: "/ˈkændɪdeɪt/", pos: "n.", ko: "후보자", ex: "She's the strongest candidate for the job." },
  { en: "clause", ipa: "/klɔːz/", pos: "n.", ko: "(계약서 등의) 조항", ex: "Read the cancellation clause carefully." },
  { en: "client", ipa: "/ˈklaɪənt/", pos: "n.", ko: "고객", ex: "We have a call with a client at noon." },
  { en: "collaborate", ipa: "/kəˈlæbəreɪt/", pos: "v.", ko: "협력하다", ex: "Our teams collaborated on the new product." },
  { en: "commission", ipa: "/kəˈmɪʃən/", pos: "n.", ko: "수수료, 커미션", ex: "Sales staff earn a commission on each sale." },
  { en: "commute", ipa: "/kəˈmjuːt/", pos: "v./n.", ko: "통근(하다)", ex: "He commutes to work by train." },
  { en: "compensation", ipa: "/ˌkɑːmpənˈseɪʃən/", pos: "n.", ko: "보상, 급여", ex: "The compensation package includes health insurance." },
  { en: "competitive", ipa: "/kəmˈpetətɪv/", pos: "adj.", ko: "경쟁력 있는", ex: "We offer competitive prices in the market." },
  { en: "compliance", ipa: "/kəmˈplaɪəns/", pos: "n.", ko: "준수", ex: "The audit checks for compliance with regulations." },
  { en: "comprise", ipa: "/kəmˈpraɪz/", pos: "v.", ko: "구성하다", ex: "The committee comprises five members." },
  { en: "confidential", ipa: "/ˌkɑːnfɪˈdenʃəl/", pos: "adj.", ko: "기밀의", ex: "This document is strictly confidential." },
  { en: "consecutive", ipa: "/kənˈsekjətɪv/", pos: "adj.", ko: "연속적인", ex: "Profits rose for the third consecutive year." },
  { en: "consolidate", ipa: "/kənˈsɑːlɪdeɪt/", pos: "v.", ko: "통합하다", ex: "The two branches will consolidate next month." },
  { en: "contract", ipa: "/ˈkɑːntrækt/", pos: "n.", ko: "계약(서)", ex: "Please sign the contract by Friday." },
  { en: "correspondence", ipa: "/ˌkɔːrəˈspɑːndəns/", pos: "n.", ko: "서신, 왕래", ex: "All correspondence should go through email." },
  { en: "cost-effective", ipa: "/ˌkɔːst ɪˈfektɪv/", pos: "adj.", ko: "비용 효율적인", ex: "This method is more cost-effective." },
  { en: "credential", ipa: "/krɪˈdenʃəl/", pos: "n.", ko: "자격 (증명)", ex: "Please submit your credentials with the application." },
  { en: "deadline", ipa: "/ˈdedlaɪn/", pos: "n.", ko: "마감 기한", ex: "The deadline for the report is Monday." },
  { en: "deduct", ipa: "/dɪˈdʌkt/", pos: "v.", ko: "공제하다", ex: "Taxes are deducted from your salary." },
  { en: "delegate", ipa: "/ˈdelɪɡeɪt/", pos: "v./n.", ko: "위임하다, 대표", ex: "A good manager knows how to delegate tasks." },
  { en: "deliverable", ipa: "/dɪˈlɪvərəbl/", pos: "n.", ko: "(프로젝트) 결과물", ex: "The first deliverable is due next week." },
  { en: "depreciate", ipa: "/dɪˈpriːʃieɪt/", pos: "v.", ko: "가치가 하락하다", ex: "New cars depreciate quickly." },
  { en: "designate", ipa: "/ˈdezɪɡneɪt/", pos: "v.", ko: "지정하다", ex: "She was designated as team leader." },
  { en: "discrepancy", ipa: "/dɪˈskrepənsi/", pos: "n.", ko: "불일치, 차이", ex: "There's a discrepancy in the invoice." },
  { en: "dispatch", ipa: "/dɪˈspætʃ/", pos: "v.", ko: "발송하다", ex: "The order will be dispatched today." },
  { en: "distribute", ipa: "/dɪˈstrɪbjuːt/", pos: "v.", ko: "배포하다, 유통하다", ex: "We distribute products across Asia." },
  { en: "diversify", ipa: "/daɪˈvɜːrsɪfaɪ/", pos: "v.", ko: "다각화하다", ex: "The company plans to diversify its products." },
  { en: "downsize", ipa: "/ˈdaʊnsaɪz/", pos: "v.", ko: "(인력을) 축소하다", ex: "The firm decided to downsize its staff." },
  { en: "draft", ipa: "/dræft/", pos: "n./v.", ko: "초안(을 작성하다)", ex: "Can you draft the email for me?" },
  { en: "eligible", ipa: "/ˈelɪdʒəbl/", pos: "adj.", ko: "자격이 있는", ex: "Full-time staff are eligible for benefits." },
  { en: "endorse", ipa: "/ɪnˈdɔːrs/", pos: "v.", ko: "지지하다, 보증하다", ex: "The CEO endorsed the new strategy." },
  { en: "enterprise", ipa: "/ˈentərpraɪz/", pos: "n.", ko: "기업", ex: "It's a small but growing enterprise." },
  { en: "entrepreneur", ipa: "/ˌɑːntrəprəˈnɜːr/", pos: "n.", ko: "사업가", ex: "She became a successful entrepreneur." },
  { en: "equity", ipa: "/ˈekwəti/", pos: "n.", ko: "지분, 자기자본", ex: "Investors received equity in the startup." },
  { en: "estimate", ipa: "/ˈestɪmeɪt/", pos: "v./n.", ko: "견적(내다), 추정하다", ex: "Can you send me an estimate first?" },
  { en: "expenditure", ipa: "/ɪkˈspendɪtʃər/", pos: "n.", ko: "지출", ex: "Government expenditure increased this year." },
  { en: "facilitate", ipa: "/fəˈsɪlɪteɪt/", pos: "v.", ko: "촉진하다, 원활하게 하다", ex: "The software facilitates team communication." },
  { en: "feasible", ipa: "/ˈfiːzəbl/", pos: "adj.", ko: "실현 가능한", ex: "Is the new plan financially feasible?" },
  { en: "finalize", ipa: "/ˈfaɪnəlaɪz/", pos: "v.", ko: "마무리 짓다", ex: "We need to finalize the contract today." },
  { en: "fiscal", ipa: "/ˈfɪskəl/", pos: "adj.", ko: "회계의, 재정의", ex: "Our fiscal year ends in December." },
  { en: "forecast", ipa: "/ˈfɔːrkæst/", pos: "n./v.", ko: "예측(하다)", ex: "The sales forecast looks promising." },
  { en: "fraud", ipa: "/frɔːd/", pos: "n.", ko: "사기", ex: "The company was accused of fraud." },
  { en: "gross", ipa: "/ɡroʊs/", pos: "adj.", ko: "총(액)의", ex: "Gross revenue rose by 10 percent." },
  { en: "hierarchy", ipa: "/ˈhaɪərɑːrki/", pos: "n.", ko: "위계, 서열", ex: "The company has a flat hierarchy." },
  { en: "implement", ipa: "/ˈɪmplɪment/", pos: "v.", ko: "시행하다", ex: "We will implement the new policy soon." },
  { en: "incentive", ipa: "/ɪnˈsentɪv/", pos: "n.", ko: "장려책, 인센티브", ex: "The bonus is a great incentive." },
  { en: "incur", ipa: "/ɪnˈkɜːr/", pos: "v.", ko: "(비용 등을) 발생시키다", ex: "Late payments incur extra fees." },
  { en: "inflation", ipa: "/ɪnˈfleɪʃən/", pos: "n.", ko: "물가 상승, 인플레이션", ex: "Inflation affects everyone's spending." },
  { en: "infrastructure", ipa: "/ˈɪnfrəstrʌktʃər/", pos: "n.", ko: "사회 기반 시설", ex: "The city invested in new infrastructure." },
  { en: "initiative", ipa: "/ɪˈnɪʃətɪv/", pos: "n.", ko: "계획, 주도권", ex: "She launched a new sustainability initiative." },
  { en: "installment", ipa: "/ɪnˈstɔːlmənt/", pos: "n.", ko: "할부, 분할 납입", ex: "You can pay in monthly installments." },
  { en: "invoice", ipa: "/ˈɪnvɔɪs/", pos: "n.", ko: "청구서, 송장", ex: "Please send the invoice to accounting." },
  { en: "itinerary", ipa: "/aɪˈtɪnəreri/", pos: "n.", ko: "여행 일정", ex: "Here's your business trip itinerary." },
  { en: "jeopardize", ipa: "/ˈdʒepərdaɪz/", pos: "v.", ko: "위태롭게 하다", ex: "The delay could jeopardize the deal." },
  { en: "joint venture", ipa: "/dʒɔɪnt ˈventʃər/", pos: "n.", ko: "합작 투자", ex: "They formed a joint venture overseas." },
  { en: "layoff", ipa: "/ˈleɪɔːf/", pos: "n.", ko: "정리해고", ex: "The company announced layoffs last week." },
  { en: "lease", ipa: "/liːs/", pos: "n./v.", ko: "임대(하다)", ex: "We lease office space downtown." },
  { en: "legislation", ipa: "/ˌledʒɪsˈleɪʃən/", pos: "n.", ko: "법률, 입법", ex: "New legislation affects small businesses." },
  { en: "leverage", ipa: "/ˈlevərɪdʒ/", pos: "v./n.", ko: "활용하다, 지렛대", ex: "We should leverage our online presence." },
  { en: "liability", ipa: "/ˌlaɪəˈbɪləti/", pos: "n.", ko: "책임, 부채", ex: "The company has limited liability." },
  { en: "logistics", ipa: "/ləˈdʒɪstɪks/", pos: "n.", ko: "물류", ex: "Logistics costs rose due to fuel prices." },
  { en: "margin", ipa: "/ˈmɑːrdʒɪn/", pos: "n.", ko: "이윤, 마진", ex: "The profit margin is quite low." },
  { en: "merger", ipa: "/ˈmɜːrdʒər/", pos: "n.", ko: "합병", ex: "The merger created a huge company." },
  { en: "milestone", ipa: "/ˈmaɪlstoʊn/", pos: "n.", ko: "중요한 단계, 이정표", ex: "Launching the app was a big milestone." },
  { en: "mitigate", ipa: "/ˈmɪtɪɡeɪt/", pos: "v.", ko: "완화하다", ex: "We took steps to mitigate the risk." },
  { en: "negotiate", ipa: "/nɪˈɡoʊʃieɪt/", pos: "v.", ko: "협상하다", ex: "They negotiated a lower price." },
  { en: "net", ipa: "/net/", pos: "adj.", ko: "순(純)의", ex: "Net income increased this quarter." },
  { en: "niche", ipa: "/nɪtʃ/", pos: "n.", ko: "틈새시장", ex: "The startup found a profitable niche." },
  { en: "nominate", ipa: "/ˈnɑːmɪneɪt/", pos: "v.", ko: "지명하다, 추천하다", ex: "She was nominated for the award." },
  { en: "obsolete", ipa: "/ˌɑːbsəˈliːt/", pos: "adj.", ko: "구식의, 쓸모없는", ex: "The old software is now obsolete." },
  { en: "outsource", ipa: "/ˈaʊtsɔːrs/", pos: "v.", ko: "외주를 주다", ex: "We outsource our customer support." },
  { en: "overhead", ipa: "/ˈoʊvərhed/", pos: "n.", ko: "간접비, 운영비", ex: "We need to reduce overhead costs." },
  { en: "oversee", ipa: "/ˌoʊvərˈsiː/", pos: "v.", ko: "감독하다", ex: "She oversees the entire production line." },
  { en: "partnership", ipa: "/ˈpɑːrtnərʃɪp/", pos: "n.", ko: "동업, 제휴", ex: "The two firms formed a partnership." },
  { en: "payroll", ipa: "/ˈpeɪroʊl/", pos: "n.", ko: "급여 명부, 급여", ex: "The payroll is processed monthly." },
  { en: "pending", ipa: "/ˈpendɪŋ/", pos: "adj.", ko: "미결의, 보류 중인", ex: "The approval is still pending." },
  { en: "portfolio", ipa: "/pɔːrtˈfoʊlioʊ/", pos: "n.", ko: "포트폴리오", ex: "She manages a large stock portfolio." },
  { en: "premises", ipa: "/ˈpremɪsɪz/", pos: "n.", ko: "부지, 구내", ex: "Visitors must sign in at the premises." },
  { en: "procurement", ipa: "/prəˈkjʊrmənt/", pos: "n.", ko: "조달, 구매", ex: "The procurement team ordered new laptops." },
  { en: "productivity", ipa: "/ˌproʊdʌkˈtɪvəti/", pos: "n.", ko: "생산성", ex: "The new tool boosted productivity." },
  { en: "proficient", ipa: "/prəˈfɪʃənt/", pos: "adj.", ko: "능숙한", ex: "She is proficient in three languages." },
  { en: "projection", ipa: "/prəˈdʒekʃən/", pos: "n.", ko: "예상, 추정", ex: "Our sales projection looks strong." },
  { en: "proposal", ipa: "/prəˈpoʊzəl/", pos: "n.", ko: "제안(서)", ex: "Please review the proposal by Friday." },
  { en: "prospective", ipa: "/prəˈspektɪv/", pos: "adj.", ko: "장래의, 유망한", ex: "We contacted several prospective clients." },
  { en: "provision", ipa: "/prəˈvɪʒən/", pos: "n.", ko: "조항, 대비", ex: "The contract includes a cancellation provision." },
  { en: "quarterly", ipa: "/ˈkwɔːrtərli/", pos: "adj./adv.", ko: "분기별의", ex: "We hold quarterly reviews." },
  { en: "quota", ipa: "/ˈkwoʊtə/", pos: "n.", ko: "할당량", ex: "He exceeded his sales quota this month." },
  { en: "rebate", ipa: "/ˈriːbeɪt/", pos: "n.", ko: "환급금", ex: "You can get a rebate on this purchase." },
  { en: "recession", ipa: "/rɪˈseʃən/", pos: "n.", ko: "경기 침체", ex: "The country entered a recession." },
  { en: "recruit", ipa: "/rɪˈkruːt/", pos: "v.", ko: "채용하다", ex: "We're recruiting new sales staff." },
  { en: "redundant", ipa: "/rɪˈdʌndənt/", pos: "adj.", ko: "정리해고된, 불필요한", ex: "Fifty workers were made redundant." },
  { en: "reimburse", ipa: "/ˌriːɪmˈbɜːrs/", pos: "v.", ko: "환급하다, 상환하다", ex: "The company will reimburse your travel costs." },
  { en: "relocate", ipa: "/riːˈloʊkeɪt/", pos: "v.", ko: "이전하다", ex: "The office will relocate next year." },
  { en: "remuneration", ipa: "/rɪˌmjuːnəˈreɪʃən/", pos: "n.", ko: "보수, 급여", ex: "The remuneration package is generous." },
  { en: "renew", ipa: "/rɪˈnuː/", pos: "v.", ko: "갱신하다", ex: "We need to renew the lease soon." },
  { en: "resign", ipa: "/rɪˈzaɪn/", pos: "v.", ko: "사임하다", ex: "She resigned from her position." },
  { en: "resolve", ipa: "/rɪˈzɑːlv/", pos: "v.", ko: "해결하다", ex: "We resolved the issue quickly." },
  { en: "resource", ipa: "/ˈriːsɔːrs/", pos: "n.", ko: "자원", ex: "We lack the resources for this project." },
  { en: "retail", ipa: "/ˈriːteɪl/", pos: "n./adj.", ko: "소매(의)", ex: "The retail price is quite high." },
  { en: "revenue", ipa: "/ˈrevənuː/", pos: "n.", ko: "수익, 매출", ex: "Revenue grew by fifteen percent." },
  { en: "reward", ipa: "/rɪˈwɔːrd/", pos: "n./v.", ko: "보상(하다)", ex: "Employees are rewarded for good performance." },
  { en: "royalty", ipa: "/ˈrɔɪəlti/", pos: "n.", ko: "로열티, 저작권료", ex: "The author receives a royalty on each book." },
  { en: "sales pitch", ipa: "/seɪlz pɪtʃ/", pos: "n.", ko: "영업 설명", ex: "He gave a convincing sales pitch." },
  { en: "sanction", ipa: "/ˈsæŋkʃən/", pos: "n./v.", ko: "제재(하다)", ex: "The country faced trade sanctions." },
  { en: "scope", ipa: "/skoʊp/", pos: "n.", ko: "범위", ex: "This is beyond the scope of the project." },
  { en: "sector", ipa: "/ˈsektər/", pos: "n.", ko: "부문, 분야", ex: "The tech sector is growing fast." },
  { en: "shareholder", ipa: "/ˈʃerhoʊldər/", pos: "n.", ko: "주주", ex: "Shareholders approved the merger." },
  { en: "shipment", ipa: "/ˈʃɪpmənt/", pos: "n.", ko: "수송(품), 선적", ex: "The shipment arrived a day late." },
  { en: "simultaneously", ipa: "/ˌsaɪmlˈteɪniəsli/", pos: "adv.", ko: "동시에", ex: "The two events happened simultaneously." },
  { en: "specification", ipa: "/ˌspesɪfɪˈkeɪʃən/", pos: "n.", ko: "사양, 명세", ex: "The product meets all specifications." },
  { en: "sponsor", ipa: "/ˈspɑːnsər/", pos: "n./v.", ko: "후원(하다)", ex: "The event is sponsored by a bank." },
  { en: "stakeholder", ipa: "/ˈsteɪkhoʊldər/", pos: "n.", ko: "이해관계자", ex: "All stakeholders were invited to the meeting." },
  { en: "streamline", ipa: "/ˈstriːmlaɪn/", pos: "v.", ko: "간소화하다", ex: "The new system streamlines the workflow." },
  { en: "subsidiary", ipa: "/səbˈsɪdieri/", pos: "n.", ko: "자회사", ex: "The company has a subsidiary in Korea." },
  { en: "subsidy", ipa: "/ˈsʌbsɪdi/", pos: "n.", ko: "보조금", ex: "Farmers receive a government subsidy." },
  { en: "surplus", ipa: "/ˈsɜːrpləs/", pos: "n.", ko: "흑자, 잉여", ex: "The company reported a trade surplus." },
  { en: "suspend", ipa: "/səˈspend/", pos: "v.", ko: "정지하다, 중단하다", ex: "The service was temporarily suspended." },
  { en: "sustainable", ipa: "/səˈsteɪnəbl/", pos: "adj.", ko: "지속 가능한", ex: "We aim for sustainable growth." },
  { en: "tariff", ipa: "/ˈtærɪf/", pos: "n.", ko: "관세", ex: "New tariffs raised import prices." },
  { en: "tenant", ipa: "/ˈtenənt/", pos: "n.", ko: "세입자", ex: "The tenant signed a two-year lease." },
  { en: "terminate", ipa: "/ˈtɜːrmɪneɪt/", pos: "v.", ko: "종료하다, 해지하다", ex: "The contract can be terminated early." },
  { en: "transaction", ipa: "/trænˈzækʃən/", pos: "n.", ko: "거래", ex: "The bank processes thousands of transactions daily." },
  { en: "turnover", ipa: "/ˈtɜːrnoʊvər/", pos: "n.", ko: "매출액, 이직률", ex: "Staff turnover has decreased this year." },
  { en: "undertake", ipa: "/ˌʌndərˈteɪk/", pos: "v.", ko: "착수하다, 맡다", ex: "The firm will undertake the new project." },
  { en: "unveil", ipa: "/ʌnˈveɪl/", pos: "v.", ko: "공개하다, 발표하다", ex: "The company unveiled its new logo." },
  { en: "utilize", ipa: "/ˈjuːtəlaɪz/", pos: "v.", ko: "활용하다", ex: "We should utilize all available resources." },
  { en: "valid", ipa: "/ˈvælɪd/", pos: "adj.", ko: "유효한", ex: "This coupon is valid until Friday." },
  { en: "venture", ipa: "/ˈventʃər/", pos: "n.", ko: "사업, 벤처", ex: "It's a risky business venture." },
  { en: "viable", ipa: "/ˈvaɪəbl/", pos: "adj.", ko: "실행 가능한", ex: "Is this a financially viable plan?" },
  { en: "warranty", ipa: "/ˈwɔːrənti/", pos: "n.", ko: "품질 보증(서)", ex: "The laptop comes with a two-year warranty." },
  { en: "workforce", ipa: "/ˈwɜːrkfɔːrs/", pos: "n.", ko: "노동 인구, 인력", ex: "The workforce has grown significantly." },
  { en: "yield", ipa: "/jiːld/", pos: "n./v.", ko: "수익(을 내다)", ex: "The bond offers a high yield." },
  { en: "accommodate", ipa: "/əˈkɑːmədeɪt/", pos: "v.", ko: "수용하다", ex: "The hotel can accommodate 200 guests." },
  { en: "advocate", ipa: "/ˈædvəkeɪt/", pos: "v./n.", ko: "옹호하다, 지지자", ex: "She advocates for flexible working hours." },
  { en: "affiliate", ipa: "/əˈfɪlieɪt/", pos: "n./v.", ko: "계열사, 제휴하다", ex: "The store is an affiliate of a larger chain." },
  { en: "ambiguous", ipa: "/æmˈbɪɡjuəs/", pos: "adj.", ko: "애매한", ex: "The instructions were a bit ambiguous." },
  { en: "amortize", ipa: "/ˈæmərtaɪz/", pos: "v.", ko: "분할 상환하다", ex: "The loan is amortized over ten years." },
  { en: "appraise", ipa: "/əˈpreɪz/", pos: "v.", ko: "평가하다", ex: "An expert appraised the property's value." },
  { en: "arbitration", ipa: "/ˌɑːrbɪˈtreɪʃən/", pos: "n.", ko: "중재", ex: "The dispute went to arbitration." },
  { en: "assess", ipa: "/əˈses/", pos: "v.", ko: "평가하다", ex: "We need to assess the risks first." },
  { en: "attrition", ipa: "/əˈtrɪʃən/", pos: "n.", ko: "(직원) 이직, 감소", ex: "The company suffers high employee attrition." },
  { en: "autonomy", ipa: "/ɔːˈtɑːnəmi/", pos: "n.", ko: "자율성", ex: "Employees value autonomy in their work." },
  { en: "beneficiary", ipa: "/ˌbenɪˈfɪʃieri/", pos: "n.", ko: "수혜자", ex: "She is the beneficiary of the policy." },
  { en: "capital", ipa: "/ˈkæpɪtl/", pos: "n.", ko: "자본", ex: "The startup needs more capital to grow." },
  { en: "clientele", ipa: "/ˌklaɪənˈtel/", pos: "n.", ko: "(전체) 고객층", ex: "The restaurant has a loyal clientele." },
  { en: "collateral", ipa: "/kəˈlætərəl/", pos: "n.", ko: "담보", ex: "The bank required collateral for the loan." },
  { en: "commodity", ipa: "/kəˈmɑːdəti/", pos: "n.", ko: "상품, 원자재", ex: "Oil is a globally traded commodity." },
  { en: "conglomerate", ipa: "/kənˈɡlɑːmərət/", pos: "n.", ko: "복합 기업", ex: "The brand is owned by a large conglomerate." },
  { en: "consensus", ipa: "/kənˈsensəs/", pos: "n.", ko: "합의", ex: "The team reached a consensus quickly." },
  { en: "constituent", ipa: "/kənˈstɪtʃuənt/", pos: "n.", ko: "구성 요소, 유권자", ex: "Plastic is a key constituent of the product." },
  { en: "contingency", ipa: "/kənˈtɪndʒənsi/", pos: "n.", ko: "만일의 사태, 대비책", ex: "We need a contingency plan." },
  { en: "counterpart", ipa: "/ˈkaʊntərpɑːrt/", pos: "n.", ko: "상대방", ex: "She met her counterpart from the other firm." },
  { en: "curb", ipa: "/kɜːrb/", pos: "v.", ko: "억제하다", ex: "The policy aims to curb spending." },
  { en: "decline", ipa: "/dɪˈklaɪn/", pos: "v./n.", ko: "감소(하다), 거절하다", ex: "Sales declined during the recession." },
  { en: "default", ipa: "/dɪˈfɔːlt/", pos: "n./v.", ko: "채무 불이행", ex: "The company defaulted on its loan." },
  { en: "deficit", ipa: "/ˈdefɪsɪt/", pos: "n.", ko: "적자", ex: "The budget deficit grew last year." },
  { en: "depreciation", ipa: "/dɪˌpriːʃiˈeɪʃən/", pos: "n.", ko: "감가상각", ex: "Depreciation is calculated annually." },
  { en: "disburse", ipa: "/dɪsˈbɜːrs/", pos: "v.", ko: "지불하다, 지급하다", ex: "Funds will be disbursed next week." },
  { en: "dividend", ipa: "/ˈdɪvɪdend/", pos: "n.", ko: "배당금", ex: "Shareholders received a dividend this year." },
  { en: "embezzle", ipa: "/ɪmˈbezl/", pos: "v.", ko: "횡령하다", ex: "He was accused of embezzling funds." },
  { en: "endorsement", ipa: "/ɪnˈdɔːrsmənt/", pos: "n.", ko: "지지, 보증", ex: "The product got a celebrity endorsement." },
  { en: "entity", ipa: "/ˈentəti/", pos: "n.", ko: "실체, 법인", ex: "The subsidiary is a separate legal entity." },
  { en: "escrow", ipa: "/ˈeskroʊ/", pos: "n.", ko: "에스크로, 위탁 계약금", ex: "The deposit is held in escrow." },
  { en: "exempt", ipa: "/ɪɡˈzempt/", pos: "adj./v.", ko: "면제된, 면제하다", ex: "Non-profits are exempt from this tax." },
  { en: "expedite", ipa: "/ˈekspədaɪt/", pos: "v.", ko: "신속히 처리하다", ex: "Please expedite this shipment." },
  { en: "franchise", ipa: "/ˈfræntʃaɪz/", pos: "n.", ko: "가맹점, 프랜차이즈", ex: "She owns a coffee shop franchise." },
  { en: "groundwork", ipa: "/ˈɡraʊndwɜːrk/", pos: "n.", ko: "기초 작업", ex: "We laid the groundwork for the deal." },
  { en: "headquarters", ipa: "/ˈhedkwɔːrtərz/", pos: "n.", ko: "본사", ex: "The headquarters is located in Seoul." },
  { en: "inventory", ipa: "/ˈɪnvəntɔːri/", pos: "n.", ko: "재고", ex: "We need to check the inventory levels." },
  { en: "lucrative", ipa: "/ˈluːkrətɪv/", pos: "adj.", ko: "수익성이 좋은", ex: "It's a highly lucrative business." },
  { en: "mandate", ipa: "/ˈmændeɪt/", pos: "n./v.", ko: "지시하다, 위임", ex: "The new law mandates safety training." },
  { en: "monopoly", ipa: "/məˈnɑːpəli/", pos: "n.", ko: "독점", ex: "The firm holds a monopoly in the region." },
  { en: "obligation", ipa: "/ˌɑːblɪˈɡeɪʃən/", pos: "n.", ko: "의무", ex: "We have a legal obligation to comply." },
  { en: "overdue", ipa: "/ˌoʊvərˈduː/", pos: "adj.", ko: "기한이 지난, 연체된", ex: "The invoice is now two weeks overdue." },
  { en: "petty cash", ipa: "/ˈpeti kæʃ/", pos: "n.", ko: "소액 현금", ex: "Use petty cash for small office expenses." },
  { en: "proceeds", ipa: "/ˈproʊsiːdz/", pos: "n.", ko: "수익금", ex: "All proceeds go to charity." },
  { en: "quorum", ipa: "/ˈkwɔːrəm/", pos: "n.", ko: "정족수", ex: "We don't have a quorum for the vote." },
  { en: "adjourn", ipa: "/əˈdʒɜːrn/", pos: "v.", ko: "휴회하다, 연기하다", ex: "The meeting was adjourned until next week." },
  { en: "affluent", ipa: "/ˈæfluənt/", pos: "adj.", ko: "부유한", ex: "The affluent suburb attracts many businesses." },
  { en: "aggregate", ipa: "/ˈæɡrɪɡeɪt/", pos: "n./adj.", ko: "합계(의), 종합의", ex: "The aggregate cost exceeded our budget." },
  { en: "align", ipa: "/əˈlaɪn/", pos: "v.", ko: "일치시키다, 맞추다", ex: "We need to align our goals with the client's." },
  { en: "allot", ipa: "/əˈlɑːt/", pos: "v.", ko: "할당하다", ex: "Each department was allotted a fixed budget." },
  { en: "amiable", ipa: "/ˈeɪmiəbl/", pos: "adj.", ko: "상냥한, 우호적인", ex: "He gave an amiable response to the criticism." },
  { en: "annex", ipa: "/əˈneks/", pos: "v./n.", ko: "부속서, 합병하다", ex: "Please refer to the annex for details." },
  { en: "antitrust", ipa: "/ˌæntiˈtrʌst/", pos: "adj.", ko: "독점 금지의", ex: "The deal faces antitrust review." },
  { en: "apprentice", ipa: "/əˈprentɪs/", pos: "n.", ko: "견습생, 수습생", ex: "He started his career as an apprentice." },
  { en: "appropriation", ipa: "/əˌproʊpriˈeɪʃən/", pos: "n.", ko: "예산 배정, 충당", ex: "The budget appropriation was approved." },
  { en: "ascertain", ipa: "/ˌæsərˈteɪn/", pos: "v.", ko: "알아내다, 확인하다", ex: "We need to ascertain the cause of the delay." },
  { en: "assortment", ipa: "/əˈsɔːrtmənt/", pos: "n.", ko: "모음, 구색", ex: "The store offers a wide assortment of goods." },
  { en: "augment", ipa: "/ɔːɡˈment/", pos: "v.", ko: "늘리다, 증가시키다", ex: "The company augmented its workforce." },
  { en: "auxiliary", ipa: "/ɔːɡˈzɪljəri/", pos: "adj.", ko: "보조의", ex: "We hired auxiliary staff for the busy season." },
  { en: "barter", ipa: "/ˈbɑːrtər/", pos: "v./n.", ko: "물물교환(하다)", ex: "The two firms agreed to barter services." },
  { en: "bespoke", ipa: "/bɪˈspoʊk/", pos: "adj.", ko: "맞춤 제작의", ex: "The firm offers bespoke software solutions." },
  { en: "bolster", ipa: "/ˈboʊlstər/", pos: "v.", ko: "강화하다, 북돋우다", ex: "The new campaign bolstered sales." },
  { en: "bottleneck", ipa: "/ˈbɑːtlnek/", pos: "n.", ko: "병목 현상", ex: "The approval process created a bottleneck." },
  { en: "brisk", ipa: "/brɪsk/", pos: "adj.", ko: "활발한", ex: "Sales have been brisk this month." },
  { en: "bulk", ipa: "/bʌlk/", pos: "n./adj.", ko: "대량(의)", ex: "We buy office supplies in bulk." },
  { en: "bureaucracy", ipa: "/bjʊˈrɑːkrəsi/", pos: "n.", ko: "관료제", ex: "The approval got stuck in bureaucracy." },
  { en: "buyout", ipa: "/ˈbaɪaʊt/", pos: "n.", ko: "기업 매수, 인수", ex: "The firm was acquired in a buyout." },
  { en: "cascade", ipa: "/kæˈskeɪd/", pos: "v.", ko: "(정보 등이) 전달되다", ex: "The policy will cascade down to every team." },
  { en: "caveat", ipa: "/ˈkæviæt/", pos: "n.", ko: "유의사항, 단서", ex: "There's one caveat in the agreement." },
  { en: "chronic", ipa: "/ˈkrɑːnɪk/", pos: "adj.", ko: "만성적인", ex: "The company faces chronic staffing shortages." },
  { en: "circulate", ipa: "/ˈsɜːrkjəleɪt/", pos: "v.", ko: "배포하다, 순환하다", ex: "Please circulate the memo to all staff." },
  { en: "cite", ipa: "/saɪt/", pos: "v.", ko: "인용하다", ex: "The report cites several recent studies." },
  { en: "coincide", ipa: "/ˌkoʊɪnˈsaɪd/", pos: "v.", ko: "동시에 일어나다", ex: "The launch coincided with the holiday season." },
  { en: "commence", ipa: "/kəˈmens/", pos: "v.", ko: "시작하다", ex: "The project will commence next Monday." },
  { en: "compile", ipa: "/kəmˈpaɪl/", pos: "v.", ko: "편집하다, 모으다", ex: "She compiled the quarterly report." },
  { en: "complement", ipa: "/ˈkɑːmplɪment/", pos: "v./n.", ko: "보완하다", ex: "The new hire complements the existing team well." },
  { en: "concede", ipa: "/kənˈsiːd/", pos: "v.", ko: "인정하다, 양보하다", ex: "He conceded that the plan had flaws." },
  { en: "concurrent", ipa: "/kənˈkɜːrənt/", pos: "adj.", ko: "동시에 발생하는", ex: "We're running two concurrent projects." },
  { en: "confer", ipa: "/kənˈfɜːr/", pos: "v.", ko: "상의하다, 수여하다", ex: "Let's confer with the legal team first." },
  { en: "congestion", ipa: "/kənˈdʒestʃən/", pos: "n.", ko: "혼잡", ex: "Traffic congestion delays deliveries." },
  { en: "consortium", ipa: "/kənˈsɔːrʃiəm/", pos: "n.", ko: "컨소시엄, 조합", ex: "A consortium of banks funded the project." },
  { en: "constraint", ipa: "/kənˈstreɪnt/", pos: "n.", ko: "제약", ex: "Budget constraints limited our options." },
  { en: "contingent", ipa: "/kənˈtɪndʒənt/", pos: "adj.", ko: "~을 조건으로 하는", ex: "The offer is contingent on approval." },
  { en: "convene", ipa: "/kənˈviːn/", pos: "v.", ko: "소집하다", ex: "The board will convene next Tuesday." },
  { en: "conversely", ipa: "/kənˈvɜːrsli/", pos: "adv.", ko: "반대로", ex: "Conversely, costs may rise if demand falls." },
  { en: "correlate", ipa: "/ˈkɔːrəleɪt/", pos: "v.", ko: "연관성이 있다", ex: "Sales correlate with advertising spend." },
  { en: "cumbersome", ipa: "/ˈkʌmbərsəm/", pos: "adj.", ko: "번거로운", ex: "The approval process is quite cumbersome." },
  { en: "curtail", ipa: "/kɜːrˈteɪl/", pos: "v.", ko: "축소하다, 삭감하다", ex: "The firm curtailed its travel budget." },
  { en: "deduction", ipa: "/dɪˈdʌkʃən/", pos: "n.", ko: "공제, 추론", ex: "You can claim a tax deduction." },
  { en: "defer", ipa: "/dɪˈfɜːr/", pos: "v.", ko: "연기하다, 미루다", ex: "We decided to defer the decision." },
  { en: "deficient", ipa: "/dɪˈfɪʃənt/", pos: "adj.", ko: "부족한", ex: "The report was deficient in key data." },
  { en: "delinquent", ipa: "/dɪˈlɪŋkwənt/", pos: "adj.", ko: "체납된, 연체된", ex: "Delinquent accounts will be charged a fee." },
  { en: "demote", ipa: "/dɪˈmoʊt/", pos: "v.", ko: "강등시키다", ex: "He was demoted after the incident." },
  { en: "denote", ipa: "/dɪˈnoʊt/", pos: "v.", ko: "나타내다, 의미하다", ex: "The asterisk denotes a required field." },
  { en: "deploy", ipa: "/dɪˈplɔɪ/", pos: "v.", ko: "배치하다, 투입하다", ex: "The firm deployed extra staff for the launch." },
  { en: "deplete", ipa: "/dɪˈpliːt/", pos: "v.", ko: "고갈시키다", ex: "The project depleted our resources quickly." },
  { en: "detrimental", ipa: "/ˌdetrɪˈmentl/", pos: "adj.", ko: "해로운", ex: "The delay was detrimental to the launch." },
  { en: "deviate", ipa: "/ˈdiːvieɪt/", pos: "v.", ko: "벗어나다, 일탈하다", ex: "We shouldn't deviate from the original plan." },
  { en: "differentiate", ipa: "/ˌdɪfəˈrenʃieɪt/", pos: "v.", ko: "차별화하다, 구별하다", ex: "The brand differentiates itself through design." },
  { en: "diligent", ipa: "/ˈdɪlɪdʒənt/", pos: "adj.", ko: "근면한", ex: "She is a diligent and reliable employee." },
  { en: "discern", ipa: "/dɪˈsɜːrn/", pos: "v.", ko: "식별하다, 분간하다", ex: "It's hard to discern a clear trend yet." },
  { en: "discretion", ipa: "/dɪˈskreʃən/", pos: "n.", ko: "재량, 신중함", ex: "The manager has discretion over the budget." },
  { en: "disperse", ipa: "/dɪˈspɜːrs/", pos: "v.", ko: "분산시키다, 흩어지다", ex: "The team is dispersed across three offices." },
  { en: "disseminate", ipa: "/dɪˈsemɪneɪt/", pos: "v.", ko: "퍼뜨리다, 배포하다", ex: "The findings were disseminated to all branches." },
  { en: "distort", ipa: "/dɪˈstɔːrt/", pos: "v.", ko: "왜곡하다", ex: "The data was distorted by a small sample." },
  { en: "divest", ipa: "/daɪˈvest/", pos: "v.", ko: "매각하다, 처분하다", ex: "The company divested its overseas branch." },
  { en: "dormant", ipa: "/ˈdɔːrmənt/", pos: "adj.", ko: "휴면 상태의", ex: "The account has been dormant for a year." },
  { en: "downturn", ipa: "/ˈdaʊntɜːrn/", pos: "n.", ko: "경기 하강", ex: "The market suffered a sharp downturn." },
  { en: "drawback", ipa: "/ˈdrɔːbæk/", pos: "n.", ko: "단점, 결점", ex: "The main drawback is the high price." },
  { en: "dwindle", ipa: "/ˈdwɪndl/", pos: "v.", ko: "줄어들다", ex: "Our reserves are starting to dwindle." },
  { en: "elicit", ipa: "/ɪˈlɪsɪt/", pos: "v.", ko: "이끌어내다", ex: "The survey elicited useful feedback." },
  { en: "emulate", ipa: "/ˈemjəleɪt/", pos: "v.", ko: "모방하다, 본받다", ex: "Smaller firms try to emulate market leaders." },
  { en: "encompass", ipa: "/ɪnˈkʌmpəs/", pos: "v.", ko: "포함하다, 아우르다", ex: "The role encompasses several departments." },
  { en: "enact", ipa: "/ɪˈnækt/", pos: "v.", ko: "제정하다", ex: "The government enacted a new labor law." },
  { en: "endeavor", ipa: "/ɪnˈdevər/", pos: "n./v.", ko: "노력, 시도하다", ex: "This is a joint endeavor between two firms." },
  { en: "enforce", ipa: "/ɪnˈfɔːrs/", pos: "v.", ko: "집행하다, 시행하다", ex: "The new rule will be strictly enforced." },
  { en: "ensue", ipa: "/ɪnˈsuː/", pos: "v.", ko: "뒤따르다, 잇따르다", ex: "Confusion ensued after the announcement." },
  { en: "entail", ipa: "/ɪnˈteɪl/", pos: "v.", ko: "수반하다", ex: "The role entails frequent travel." },
  { en: "envisage", ipa: "/ɪnˈvɪzɪdʒ/", pos: "v.", ko: "예상하다, 구상하다", ex: "We envisage strong growth next year." },
  { en: "equate", ipa: "/ɪˈkweɪt/", pos: "v.", ko: "동일시하다", ex: "Don't equate price with quality." },
  { en: "erode", ipa: "/ɪˈroʊd/", pos: "v.", ko: "약화시키다, 침식하다", ex: "Trust was eroded by the scandal." },
  { en: "escalate", ipa: "/ˈeskəleɪt/", pos: "v.", ko: "확대되다, 상승하다", ex: "Costs escalated during construction." },
  { en: "evade", ipa: "/ɪˈveɪd/", pos: "v.", ko: "회피하다", ex: "The firm was accused of evading taxes." },
  { en: "exemplary", ipa: "/ɪɡˈzempləri/", pos: "adj.", ko: "모범적인", ex: "Her performance has been exemplary." },
  { en: "exert", ipa: "/ɪɡˈzɜːrt/", pos: "v.", ko: "행사하다, 발휘하다", ex: "The manager exerted pressure to meet deadlines." },
  { en: "expend", ipa: "/ɪkˈspend/", pos: "v.", ko: "소비하다, 지출하다", ex: "We expended a lot of effort on this deal." },
  { en: "expertise", ipa: "/ˌekspɜːrˈtiːz/", pos: "n.", ko: "전문성", ex: "We rely on her technical expertise." },
  { en: "expire", ipa: "/ɪkˈspaɪər/", pos: "v.", ko: "만료되다", ex: "Your membership will expire next month." },
  { en: "fabricate", ipa: "/ˈfæbrɪkeɪt/", pos: "v.", ko: "조작하다, 날조하다", ex: "He was fired for fabricating expense reports." },
  { en: "falter", ipa: "/ˈfɔːltər/", pos: "v.", ko: "휘청거리다, 흔들리다", ex: "The economy began to falter last quarter." },
  { en: "feasibility", ipa: "/ˌfiːzəˈbɪləti/", pos: "n.", ko: "실현 가능성", ex: "We conducted a feasibility study first." },
  { en: "flagship", ipa: "/ˈflæɡʃɪp/", pos: "n./adj.", ko: "주력의, 대표 상품", ex: "This store is the brand's flagship location." },
  { en: "fluctuation", ipa: "/ˌflʌktʃuˈeɪʃən/", pos: "n.", ko: "변동", ex: "Currency fluctuation affects our profits." },
  { en: "forfeit", ipa: "/ˈfɔːrfɪt/", pos: "v.", ko: "몰수당하다, 상실하다", ex: "Late applicants forfeit their deposit." },
  { en: "formulate", ipa: "/ˈfɔːrmjəleɪt/", pos: "v.", ko: "공식화하다, 수립하다", ex: "The team formulated a new strategy." },
  { en: "fortify", ipa: "/ˈfɔːrtɪfaɪ/", pos: "v.", ko: "강화하다", ex: "The firm fortified its market position." },
  { en: "foster", ipa: "/ˈfɔːstər/", pos: "v.", ko: "육성하다, 조성하다", ex: "The program fosters innovation among staff." },
  { en: "fragmented", ipa: "/ˈfræɡmentɪd/", pos: "adj.", ko: "분열된, 파편화된", ex: "The market is highly fragmented." },
  { en: "frugal", ipa: "/ˈfruːɡəl/", pos: "adj.", ko: "검소한, 절약하는", ex: "The startup took a frugal approach to spending." },
  { en: "fulfill", ipa: "/fʊlˈfɪl/", pos: "v.", ko: "이행하다, 충족시키다", ex: "We aim to fulfill every customer order on time." },
  { en: "furnish", ipa: "/ˈfɜːrnɪʃ/", pos: "v.", ko: "제공하다, 비치하다", ex: "Please furnish the required documents." },
  { en: "gauge", ipa: "/ɡeɪdʒ/", pos: "v./n.", ko: "가늠하다, 측정하다", ex: "We surveyed clients to gauge satisfaction." },
  { en: "glitch", ipa: "/ɡlɪtʃ/", pos: "n.", ko: "결함, 오류", ex: "A technical glitch delayed the launch." },
  { en: "grapple", ipa: "/ˈɡræpl/", pos: "v.", ko: "씨름하다, 대처하다", ex: "The industry is grappling with new regulations." },
  { en: "groundbreaking", ipa: "/ˈɡraʊndbreɪkɪŋ/", pos: "adj.", ko: "획기적인", ex: "It was a groundbreaking new product." },
  { en: "hamper", ipa: "/ˈhæmpər/", pos: "v.", ko: "방해하다", ex: "Bad weather hampered the delivery schedule." },
  { en: "hasten", ipa: "/ˈheɪsn/", pos: "v.", ko: "재촉하다, 서두르다", ex: "The news hastened the decision to merge." },
  { en: "headcount", ipa: "/ˈhedkaʊnt/", pos: "n.", ko: "인원수", ex: "The department's headcount grew this year." },
  { en: "hinder", ipa: "/ˈhɪndər/", pos: "v.", ko: "방해하다", ex: "Poor communication hindered the project." },
  { en: "hype", ipa: "/haɪp/", pos: "n./v.", ko: "과대광고, 띄우다", ex: "There's a lot of hype around the new phone." },
  { en: "immerse", ipa: "/ɪˈmɜːrs/", pos: "v.", ko: "몰입시키다", ex: "New hires are immersed in training." },
  { en: "impede", ipa: "/ɪmˈpiːd/", pos: "v.", ko: "지연시키다, 방해하다", ex: "Red tape impeded the approval process." },
  { en: "imperative", ipa: "/ɪmˈperətɪv/", pos: "adj./n.", ko: "필수적인", ex: "It's imperative that we meet the deadline." },
  { en: "implicit", ipa: "/ɪmˈplɪsɪt/", pos: "adj.", ko: "암묵적인", ex: "There was an implicit agreement between them." },
  { en: "incentivize", ipa: "/ɪnˈsentɪvaɪz/", pos: "v.", ko: "동기를 부여하다", ex: "Bonuses incentivize better performance." },
  { en: "inception", ipa: "/ɪnˈsepʃən/", pos: "n.", ko: "시작, 개시", ex: "Sales have grown steadily since inception." },
  { en: "incremental", ipa: "/ˌɪnkrəˈmentl/", pos: "adj.", ko: "점진적인", ex: "We made incremental improvements each month." },
  { en: "indispensable", ipa: "/ˌɪndɪˈspensəbl/", pos: "adj.", ko: "필수 불가결한", ex: "Reliable data is indispensable for planning." },
  { en: "induce", ipa: "/ɪnˈduːs/", pos: "v.", ko: "유도하다, 유발하다", ex: "Discounts induce customers to buy more." },
  { en: "infringe", ipa: "/ɪnˈfrɪndʒ/", pos: "v.", ko: "침해하다", ex: "The logo infringes on another company's trademark." },
  { en: "ingenuity", ipa: "/ˌɪndʒəˈnuːəti/", pos: "n.", ko: "독창성", ex: "The design shows real engineering ingenuity." },
  { en: "inhibit", ipa: "/ɪnˈhɪbɪt/", pos: "v.", ko: "억제하다", ex: "High costs inhibit small firms from expanding." },
  { en: "initiate", ipa: "/ɪˈnɪʃieɪt/", pos: "v.", ko: "시작하다, 개시하다", ex: "The company initiated a new hiring drive." },
  { en: "innovate", ipa: "/ˈɪnəveɪt/", pos: "v.", ko: "혁신하다", ex: "Firms must innovate to stay competitive." },
  { en: "insolvent", ipa: "/ɪnˈsɑːlvənt/", pos: "adj.", ko: "지급 불능의, 파산한", ex: "The retailer became insolvent last year." },
  { en: "integral", ipa: "/ˈɪntɪɡrəl/", pos: "adj.", ko: "필수적인, 필수불가결한", ex: "Testing is integral to the process." },
  { en: "interim", ipa: "/ˈɪntərɪm/", pos: "adj./n.", ko: "임시의, 중간의", ex: "She was named interim CEO." },
  { en: "intermediary", ipa: "/ˌɪntərˈmiːdieri/", pos: "n.", ko: "중개인, 중개자", ex: "The broker acts as an intermediary." },
  { en: "intricate", ipa: "/ˈɪntrɪkət/", pos: "adj.", ko: "복잡한, 정교한", ex: "The supply chain is quite intricate." },
  { en: "intrinsic", ipa: "/ɪnˈtrɪnzɪk/", pos: "adj.", ko: "본질적인, 내재된", ex: "The asset's intrinsic value is hard to assess." },
  { en: "invalidate", ipa: "/ɪnˈvælɪdeɪt/", pos: "v.", ko: "무효화하다", ex: "The error invalidated the entire contract." },
  { en: "irrespective", ipa: "/ˌɪrɪˈspektɪv/", pos: "adj.", ko: "관계없이", ex: "All staff get a bonus, irrespective of rank." },
  { en: "iterate", ipa: "/ˈɪtəreɪt/", pos: "v.", ko: "반복하다, 개선을 거듭하다", ex: "The team iterates on the design weekly." },
  { en: "jointly", ipa: "/ˈdʒɔɪntli/", pos: "adv.", ko: "공동으로", ex: "The two firms jointly own the patent." },
  { en: "jurisdiction", ipa: "/ˌdʒʊrɪsˈdɪkʃən/", pos: "n.", ko: "관할권", ex: "This falls outside the court's jurisdiction." },
  { en: "keen", ipa: "/kiːn/", pos: "adj.", ko: "열심인, 예리한", ex: "She's keen to take on more responsibility." },
  { en: "lag", ipa: "/læɡ/", pos: "v./n.", ko: "뒤처지다, 지연", ex: "Our sales lag behind the market leader." },
  { en: "latent", ipa: "/ˈleɪtnt/", pos: "adj.", ko: "잠재적인", ex: "The survey revealed latent customer demand." },
  { en: "levy", ipa: "/ˈlevi/", pos: "v./n.", ko: "부과하다, 세금", ex: "The city levies a tax on tourism." },
  { en: "liaison", ipa: "/liˈeɪzɑːn/", pos: "n.", ko: "연락 담당, 연계", ex: "She serves as the liaison between teams." },
  { en: "liquidate", ipa: "/ˈlɪkwɪdeɪt/", pos: "v.", ko: "청산하다", ex: "The firm decided to liquidate its assets." },
  { en: "litigation", ipa: "/ˌlɪtɪˈɡeɪʃən/", pos: "n.", ko: "소송", ex: "The dispute resulted in lengthy litigation." },
  { en: "longevity", ipa: "/lɑːnˈdʒevəti/", pos: "n.", ko: "장기 근속, 수명", ex: "The firm values employee longevity." },
  { en: "magnitude", ipa: "/ˈmæɡnɪtuːd/", pos: "n.", ko: "규모, 중요도", ex: "We underestimated the magnitude of the task." },
  { en: "mainstream", ipa: "/ˈmeɪnstriːm/", pos: "adj./n.", ko: "주류의", ex: "The product finally went mainstream." },
  { en: "mandatory", ipa: "/ˈmændətɔːri/", pos: "adj.", ko: "의무적인, 필수의", ex: "Safety training is mandatory for all staff." },
  { en: "manifest", ipa: "/ˈmænɪfest/", pos: "v./adj.", ko: "나타나다, 명백한", ex: "Problems began to manifest after launch." },
  { en: "marginal", ipa: "/ˈmɑːrdʒɪnəl/", pos: "adj.", ko: "미미한, 한계의", ex: "The change had only a marginal effect." },
  { en: "markup", ipa: "/ˈmɑːrkʌp/", pos: "n.", ko: "가격 인상폭, 이윤", ex: "Retailers apply a standard markup." },
  { en: "materialize", ipa: "/məˈtɪriəlaɪz/", pos: "v.", ko: "실현되다, 나타나다", ex: "The expected growth never materialized." },
  { en: "maturity", ipa: "/məˈtʃʊrəti/", pos: "n.", ko: "만기, 성숙", ex: "The bond reaches maturity in five years." },
  { en: "meticulous", ipa: "/məˈtɪkjələs/", pos: "adj.", ko: "꼼꼼한", ex: "She is meticulous about details." },
  { en: "mobilize", ipa: "/ˈmoʊbəlaɪz/", pos: "v.", ko: "동원하다", ex: "The company mobilized resources quickly." },
  { en: "moderate", ipa: "/ˈmɑːdərət/", pos: "adj./v.", ko: "적당한, 완화하다", ex: "We expect moderate growth this year." },
  { en: "monetary", ipa: "/ˈmɑːnəteri/", pos: "adj.", ko: "금전적인, 통화의", ex: "There's a monetary reward for referrals." },
  { en: "mortgage", ipa: "/ˈmɔːrɡɪdʒ/", pos: "n.", ko: "담보 대출", ex: "They took out a mortgage on the office." },
  { en: "negligence", ipa: "/ˈneɡlɪdʒəns/", pos: "n.", ko: "과실, 태만", ex: "The lawsuit alleges corporate negligence." },
  { en: "negligible", ipa: "/ˈneɡlɪdʒəbl/", pos: "adj.", ko: "무시할 만한", ex: "The price difference is negligible." },
  { en: "nonetheless", ipa: "/ˌnʌnðəˈles/", pos: "adv.", ko: "그럼에도 불구하고", ex: "Sales fell; nonetheless, profits rose." },
  { en: "nurture", ipa: "/ˈnɜːrtʃər/", pos: "v.", ko: "육성하다, 키우다", ex: "The mentor program nurtures young talent." },
  { en: "obsolescence", ipa: "/ˌɑːbsəˈlesns/", pos: "n.", ko: "노후화, 진부화", ex: "Rapid tech change causes early obsolescence." },
  { en: "offset", ipa: "/ˈɔːfset/", pos: "v./n.", ko: "상쇄하다", ex: "Higher sales offset the rising costs." },
  { en: "ongoing", ipa: "/ˈɑːnɡoʊɪŋ/", pos: "adj.", ko: "진행 중인", ex: "Negotiations are still ongoing." },
  { en: "onset", ipa: "/ˈɑːnset/", pos: "n.", ko: "시작, 개시", ex: "Demand rose sharply at the onset of winter." },
  { en: "optimal", ipa: "/ˈɑːptɪməl/", pos: "adj.", ko: "최적의", ex: "We're seeking the optimal solution." },
  { en: "optimize", ipa: "/ˈɑːptɪmaɪz/", pos: "v.", ko: "최적화하다", ex: "We optimized the workflow to save time." },
  { en: "outlay", ipa: "/ˈaʊtleɪ/", pos: "n.", ko: "지출, 경비", ex: "The initial outlay was higher than expected." },
  { en: "outperform", ipa: "/ˌaʊtpərˈfɔːrm/", pos: "v.", ko: "능가하다, 더 나은 성과를 내다", ex: "Our stock outperformed the market." },
  { en: "outreach", ipa: "/ˈaʊtriːtʃ/", pos: "n.", ko: "지원 활동, 봉사 활동", ex: "The firm runs a community outreach program." },
  { en: "overdraft", ipa: "/ˈoʊvərdræft/", pos: "n.", ko: "초과 인출, 마이너스 통장", ex: "The account went into overdraft." },
  { en: "overhaul", ipa: "/ˈoʊvərhɔːl/", pos: "v./n.", ko: "정비하다, 대대적인 개편", ex: "The system needs a complete overhaul." },
  { en: "oversight", ipa: "/ˈoʊvərsaɪt/", pos: "n.", ko: "감독, 실수", ex: "The board provides financial oversight." },
  { en: "overrun", ipa: "/ˌoʊvərˈrʌn/", pos: "v./n.", ko: "초과하다, 초과액", ex: "The project suffered a serious cost overrun." },
  { en: "paradigm", ipa: "/ˈpærədaɪm/", pos: "n.", ko: "패러다임, 전형적인 예", ex: "This marks a paradigm shift in retail." },
  { en: "parameter", ipa: "/pəˈræmɪtər/", pos: "n.", ko: "기준, 매개변수", ex: "Set clear parameters for the project scope." },
  { en: "penalize", ipa: "/ˈpiːnəlaɪz/", pos: "v.", ko: "불이익을 주다, 처벌하다", ex: "Late submissions will be penalized." },
  { en: "persuade", ipa: "/pərˈsweɪd/", pos: "v.", ko: "설득하다", ex: "She persuaded the board to approve the plan." },
  { en: "pertain", ipa: "/pərˈteɪn/", pos: "v.", ko: "관련되다", ex: "This clause pertains to overseas sales." },
  { en: "pinpoint", ipa: "/ˈpɪnpɔɪnt/", pos: "v.", ko: "정확히 짚어내다", ex: "We need to pinpoint the cause of the error." },
  { en: "pivotal", ipa: "/ˈpɪvətl/", pos: "adj.", ko: "중추적인, 중요한", ex: "This quarter is pivotal for the company." },
  { en: "plausible", ipa: "/ˈplɔːzəbl/", pos: "adj.", ko: "그럴듯한", ex: "That's a plausible explanation for the drop." },
  { en: "plummet", ipa: "/ˈplʌmɪt/", pos: "v.", ko: "급락하다", ex: "The stock price plummeted overnight." },
  { en: "precaution", ipa: "/prɪˈkɔːʃən/", pos: "n.", ko: "예방 조치", ex: "We took precautions to avoid delays." },
  { en: "precedent", ipa: "/ˈpresɪdənt/", pos: "n.", ko: "선례", ex: "This ruling sets an important precedent." },
  { en: "predecessor", ipa: "/ˈpredəsesər/", pos: "n.", ko: "전임자", ex: "She replaced her predecessor last spring." },
  { en: "preempt", ipa: "/priˈempt/", pos: "v.", ko: "선점하다, 미연에 방지하다", ex: "The firm preempted the rumor with a statement." },
  { en: "prerequisite", ipa: "/priˈrekwəzɪt/", pos: "n.", ko: "필수 조건", ex: "Experience is a prerequisite for this role." },
  { en: "prestige", ipa: "/preˈstiːʒ/", pos: "n.", ko: "명성, 위신", ex: "The award adds prestige to the brand." },
  { en: "prevalent", ipa: "/ˈprevələnt/", pos: "adj.", ko: "널리 퍼진, 일반적인", ex: "Remote work is prevalent in this industry." },
  { en: "proactive", ipa: "/proʊˈæktɪv/", pos: "adj.", ko: "적극적인, 선제적인", ex: "We took a proactive approach to the issue." },
  { en: "probation", ipa: "/proʊˈbeɪʃən/", pos: "n.", ko: "수습 기간, 견습 기간", ex: "New hires undergo a three-month probation." },
  { en: "procure", ipa: "/prəˈkjʊr/", pos: "v.", ko: "조달하다, 확보하다", ex: "We procure materials from local suppliers." },
  { en: "prolong", ipa: "/prəˈlɔːŋ/", pos: "v.", ko: "연장하다", ex: "The delay prolonged the negotiation." },
  { en: "prone", ipa: "/proʊn/", pos: "adj.", ko: "~하기 쉬운, 경향이 있는", ex: "The old system is prone to errors." },
  { en: "propel", ipa: "/prəˈpel/", pos: "v.", ko: "추진하다", ex: "The campaign propelled sales upward." },
  { en: "protocol", ipa: "/ˈproʊtəkɔːl/", pos: "n.", ko: "규약, 프로토콜", ex: "Follow the safety protocol at all times." },
  { en: "prudent", ipa: "/ˈpruːdnt/", pos: "adj.", ko: "신중한", ex: "It's prudent to save part of the profit." },
  { en: "punctual", ipa: "/ˈpʌŋktʃuəl/", pos: "adj.", ko: "시간을 잘 지키는", ex: "She is always punctual for meetings." },
  { en: "quantify", ipa: "/ˈkwɑːntɪfaɪ/", pos: "v.", ko: "수치화하다, 정량화하다", ex: "It's hard to quantify customer loyalty." },
  { en: "rally", ipa: "/ˈræli/", pos: "v./n.", ko: "회복하다, 반등하다", ex: "The market rallied after the announcement." },
  { en: "rationale", ipa: "/ˌræʃəˈnæl/", pos: "n.", ko: "근거, 이유", ex: "Explain the rationale behind the decision." },
  { en: "realign", ipa: "/ˌriːəˈlaɪn/", pos: "v.", ko: "재편성하다", ex: "The company realigned its departments." },
  { en: "rebound", ipa: "/rɪˈbaʊnd/", pos: "v./n.", ko: "반등하다, 회복하다", ex: "Sales rebounded after the slow quarter." },
  { en: "recoup", ipa: "/rɪˈkuːp/", pos: "v.", ko: "회수하다, 만회하다", ex: "The firm hopes to recoup its investment." },
  { en: "rectify", ipa: "/ˈrektɪfaɪ/", pos: "v.", ko: "바로잡다", ex: "We must rectify the billing error." },
  { en: "redeem", ipa: "/rɪˈdiːm/", pos: "v.", ko: "상환하다, 교환하다", ex: "Customers can redeem points for discounts." },
  { en: "reinstate", ipa: "/ˌriːɪnˈsteɪt/", pos: "v.", ko: "복직시키다, 복원하다", ex: "The employee was reinstated after review." },
  { en: "reiterate", ipa: "/riˈɪtəreɪt/", pos: "v.", ko: "반복해서 말하다", ex: "Let me reiterate our main goal." },
  { en: "relinquish", ipa: "/rɪˈlɪŋkwɪʃ/", pos: "v.", ko: "포기하다, 넘겨주다", ex: "She relinquished her role as manager." },
  { en: "remedy", ipa: "/ˈremədi/", pos: "n./v.", ko: "해결책, 개선하다", ex: "We found a quick remedy for the issue." },
  { en: "render", ipa: "/ˈrendər/", pos: "v.", ko: "~하게 만들다, 제공하다", ex: "The update rendered the old app useless." },
  { en: "renegotiate", ipa: "/ˌriːnɪˈɡoʊʃieɪt/", pos: "v.", ko: "재협상하다", ex: "We plan to renegotiate the contract terms." },
  { en: "replenish", ipa: "/rɪˈplenɪʃ/", pos: "v.", ko: "보충하다", ex: "We need to replenish our stock soon." },
  { en: "reprimand", ipa: "/ˈreprɪmænd/", pos: "v./n.", ko: "질책하다, 견책", ex: "He was reprimanded for the mistake." },
  { en: "resilient", ipa: "/rɪˈzɪliənt/", pos: "adj.", ko: "회복력 있는", ex: "The business proved resilient during the crisis." },
  { en: "resonate", ipa: "/ˈrezəneɪt/", pos: "v.", ko: "공감을 얻다, 반향을 일으키다", ex: "The message resonated with customers." },
  { en: "restructure", ipa: "/riːˈstrʌktʃər/", pos: "v.", ko: "구조 조정하다", ex: "The firm restructured its debt last year." },
  { en: "retract", ipa: "/rɪˈtrækt/", pos: "v.", ko: "철회하다", ex: "The company retracted its earlier statement." },
  { en: "revamp", ipa: "/riːˈvæmp/", pos: "v.", ko: "개편하다, 손질하다", ex: "We're revamping our website this month." },
  { en: "revoke", ipa: "/rɪˈvoʊk/", pos: "v.", ko: "취소하다, 철회하다", ex: "The license was revoked after the audit." },
  { en: "rigorous", ipa: "/ˈrɪɡərəs/", pos: "adj.", ko: "엄격한, 철저한", ex: "The product goes through rigorous testing." },
  { en: "robust", ipa: "/roʊˈbʌst/", pos: "adj.", ko: "탄탄한, 견고한", ex: "The company reported robust earnings." },
  { en: "salvage", ipa: "/ˈsælvɪdʒ/", pos: "v./n.", ko: "구제하다, 회수하다", ex: "They tried to salvage the failing deal." },
  { en: "scrutinize", ipa: "/ˈskruːtənaɪz/", pos: "v.", ko: "면밀히 조사하다", ex: "Auditors scrutinize every transaction." },
  { en: "sluggish", ipa: "/ˈslʌɡɪʃ/", pos: "adj.", ko: "부진한, 둔한", ex: "Sales have been sluggish this quarter." },
  { en: "solicit", ipa: "/səˈlɪsɪt/", pos: "v.", ko: "요청하다, 간청하다", ex: "We solicited feedback from all employees." },
  { en: "solvent", ipa: "/ˈsɑːlvənt/", pos: "adj.", ko: "지급 능력이 있는", ex: "The company remains solvent despite losses." },
  { en: "spearhead", ipa: "/ˈspɪrhed/", pos: "v.", ko: "선두에서 이끌다", ex: "She spearheaded the new marketing campaign." },
  { en: "speculate", ipa: "/ˈspekjəleɪt/", pos: "v.", ko: "추측하다, 투기하다", ex: "Analysts speculate about future prices." },
  { en: "spike", ipa: "/spaɪk/", pos: "n./v.", ko: "급등, 급증하다", ex: "There was a spike in demand last week." },
  { en: "sporadic", ipa: "/spəˈrædɪk/", pos: "adj.", ko: "산발적인", ex: "We've had sporadic reports of the issue." },
  { en: "stagnant", ipa: "/ˈstæɡnənt/", pos: "adj.", ko: "침체된, 정체된", ex: "Wages have remained stagnant for years." },
  { en: "staple", ipa: "/ˈsteɪpl/", pos: "n./adj.", ko: "주요 상품, 필수품인", ex: "Rice is a staple in many diets." },
  { en: "statutory", ipa: "/ˈstætʃətɔːri/", pos: "adj.", ko: "법정의, 법적인", ex: "Employees get the statutory minimum leave." },
  { en: "stipulate", ipa: "/ˈstɪpjəleɪt/", pos: "v.", ko: "규정하다, 명시하다", ex: "The contract stipulates a 30-day notice." },
  { en: "stringent", ipa: "/ˈstrɪndʒənt/", pos: "adj.", ko: "엄격한", ex: "The new rules are far more stringent." },
  { en: "subdued", ipa: "/səbˈduːd/", pos: "adj.", ko: "가라앉은, 억제된", ex: "Demand remained subdued throughout the year." },
  { en: "subordinate", ipa: "/səˈbɔːrdɪnət/", pos: "n./adj.", ko: "부하 직원, 하위의", ex: "She delegates tasks to her subordinates." },
  { en: "subsidize", ipa: "/ˈsʌbsɪdaɪz/", pos: "v.", ko: "보조금을 지급하다", ex: "The government subsidizes renewable energy." },
  { en: "substantiate", ipa: "/səbˈstænʃieɪt/", pos: "v.", ko: "입증하다", ex: "We need data to substantiate the claim." },
  { en: "succinct", ipa: "/səkˈsɪŋkt/", pos: "adj.", ko: "간결한", ex: "Keep your report succinct and clear." },
  { en: "surge", ipa: "/sɜːrdʒ/", pos: "n./v.", ko: "급증, 급증하다", ex: "There was a surge in online orders." },
  { en: "surpass", ipa: "/sərˈpæs/", pos: "v.", ko: "능가하다", ex: "This year's revenue surpassed all forecasts." },
  { en: "susceptible", ipa: "/səˈseptəbl/", pos: "adj.", ko: "영향받기 쉬운", ex: "Small firms are susceptible to market shocks." },
  { en: "tangible", ipa: "/ˈtændʒəbl/", pos: "adj.", ko: "실질적인, 유형의", ex: "We need tangible results by year-end." },
  { en: "tedious", ipa: "/ˈtiːdiəs/", pos: "adj.", ko: "지루한, 지겨운", ex: "Filing expense reports can be tedious." },
  { en: "thereby", ipa: "/ˌðerˈbaɪ/", pos: "adv.", ko: "그렇게 함으로써", ex: "We cut costs, thereby raising profits." },
  { en: "threshold", ipa: "/ˈθreʃhoʊld/", pos: "n.", ko: "기준점, 문턱", ex: "Sales passed the threshold for a bonus." },
  { en: "thrive", ipa: "/θraɪv/", pos: "v.", ko: "번창하다", ex: "The business thrived despite competition." },
  { en: "trajectory", ipa: "/trəˈdʒektəri/", pos: "n.", ko: "궤도, 추세", ex: "The company is on a strong growth trajectory." },
  { en: "tranche", ipa: "/træntʃ/", pos: "n.", ko: "부분, 분할 발행분", ex: "The loan is paid out in three tranches." },
  { en: "transient", ipa: "/ˈtrænʃənt/", pos: "adj.", ko: "일시적인", ex: "The price spike was transient." },
  { en: "transparent", ipa: "/trænsˈpærənt/", pos: "adj.", ko: "투명한", ex: "The firm is transparent about its pricing." },
  { en: "turbulent", ipa: "/ˈtɜːrbjələnt/", pos: "adj.", ko: "격동의, 불안정한", ex: "It was a turbulent year for the industry." },
  { en: "undergo", ipa: "/ˌʌndərˈɡoʊ/", pos: "v.", ko: "겪다, 거치다", ex: "The company is undergoing major changes." },
  { en: "underlying", ipa: "/ˌʌndərˈlaɪɪŋ/", pos: "adj.", ko: "근본적인, 기저의", ex: "We must address the underlying cause." },
  { en: "underpin", ipa: "/ˌʌndərˈpɪn/", pos: "v.", ko: "뒷받침하다", ex: "Strong demand underpins the forecast." },
  { en: "undervalue", ipa: "/ˌʌndərˈvæljuː/", pos: "v.", ko: "저평가하다", ex: "Investors may be undervaluing the stock." },
  { en: "unify", ipa: "/ˈjuːnɪfaɪ/", pos: "v.", ko: "통합하다, 통일하다", ex: "The merger will unify the two brands." },
  { en: "untapped", ipa: "/ʌnˈtæpt/", pos: "adj.", ko: "미개척의", ex: "There's an untapped market overseas." },
  { en: "upfront", ipa: "/ʌpˈfrʌnt/", pos: "adj./adv.", ko: "선불의, 선불로", ex: "Payment is required upfront." },
  { en: "uphold", ipa: "/ʌpˈhoʊld/", pos: "v.", ko: "지지하다, 유지하다", ex: "The court upheld the original ruling." },
  { en: "versatile", ipa: "/ˈvɜːrsətl/", pos: "adj.", ko: "다재다능한, 다용도의", ex: "She's a versatile employee who adapts fast." },
  { en: "vigilant", ipa: "/ˈvɪdʒɪlənt/", pos: "adj.", ko: "경계하는, 방심하지 않는", ex: "Stay vigilant against phishing emails." },
  { en: "vulnerable", ipa: "/ˈvʌlnərəbl/", pos: "adj.", ko: "취약한", ex: "Small businesses are vulnerable to price shocks." },
  { en: "wane", ipa: "/weɪn/", pos: "v.", ko: "약해지다, 줄어들다", ex: "Interest in the product began to wane." },
  { en: "warrant", ipa: "/ˈwɔːrənt/", pos: "v./n.", ko: "정당화하다, 보증하다", ex: "The results warrant further investigation." },
  { en: "waive", ipa: "/weɪv/", pos: "v.", ko: "포기하다, 면제하다", ex: "The bank agreed to waive the late fee." },
  { en: "wholesale", ipa: "/ˈhoʊlseɪl/", pos: "n./adj.", ko: "도매(의)", ex: "We buy directly from a wholesale supplier." },
  { en: "withhold", ipa: "/wɪðˈhoʊld/", pos: "v.", ko: "보류하다, 원천징수하다", ex: "Taxes are withheld from every paycheck." },
  { en: "workflow", ipa: "/ˈwɜːrkfloʊ/", pos: "n.", ko: "작업 흐름", ex: "The new tool improved our workflow." },
  { en: "worthwhile", ipa: "/ˌwɜːrθˈwaɪl/", pos: "adj.", ko: "가치 있는", ex: "The training turned out to be worthwhile." },
];

if (typeof module !== "undefined") {
  module.exports = WORD_BANK;
}
