// 단어 데이터베이스: 매일 20개씩 순환하며 학습합니다.
// 각 항목: en(영단어), ko(뜻), pos(품사), ex(예문)
const WORD_BANK = [
  { en: "abandon", ko: "버리다, 포기하다", pos: "v.", ex: "He had to abandon his car in the snow." },
  { en: "ability", ko: "능력", pos: "n.", ex: "She has the ability to solve hard problems." },
  { en: "absorb", ko: "흡수하다", pos: "v.", ex: "Plants absorb water through their roots." },
  { en: "abstract", ko: "추상적인", pos: "adj.", ex: "It's an abstract idea, hard to picture." },
  { en: "abundant", ko: "풍부한", pos: "adj.", ex: "The region has abundant natural resources." },
  { en: "accelerate", ko: "가속하다", pos: "v.", ex: "The car began to accelerate on the highway." },
  { en: "accompany", ko: "동행하다", pos: "v.", ex: "She asked a friend to accompany her." },
  { en: "accurate", ko: "정확한", pos: "adj.", ex: "We need accurate data before deciding." },
  { en: "achieve", ko: "성취하다", pos: "v.", ex: "He worked hard to achieve his goal." },
  { en: "acknowledge", ko: "인정하다", pos: "v.", ex: "She acknowledged her mistake right away." },
  { en: "adapt", ko: "적응하다", pos: "v.", ex: "Animals adapt to their environment over time." },
  { en: "adequate", ko: "충분한, 적절한", pos: "adj.", ex: "We don't have adequate time to finish." },
  { en: "adjust", ko: "조정하다", pos: "v.", ex: "Please adjust the volume a little." },
  { en: "advocate", ko: "옹호하다, 지지자", pos: "v./n.", ex: "She is an advocate for equal rights." },
  { en: "aggressive", ko: "공격적인", pos: "adj.", ex: "The dog became aggressive toward strangers." },
  { en: "allocate", ko: "할당하다", pos: "v.", ex: "The manager will allocate the budget." },
  { en: "ambiguous", ko: "모호한", pos: "adj.", ex: "The instructions were ambiguous and confusing." },
  { en: "analyze", ko: "분석하다", pos: "v.", ex: "Scientists analyze the data carefully." },
  { en: "anticipate", ko: "예상하다", pos: "v.", ex: "We anticipate strong demand next year." },
  { en: "apparent", ko: "분명한, 명백한", pos: "adj.", ex: "It became apparent that he was tired." },
  { en: "appreciate", ko: "감사하다, 진가를 알다", pos: "v.", ex: "I really appreciate your help today." },
  { en: "approach", ko: "접근하다, 접근법", pos: "v./n.", ex: "Let's try a different approach." },
  { en: "appropriate", ko: "적절한", pos: "adj.", ex: "That behavior isn't appropriate at work." },
  { en: "arbitrary", ko: "임의의", pos: "adj.", ex: "The rule seemed completely arbitrary." },
  { en: "arise", ko: "발생하다", pos: "v.", ex: "New problems may arise later on." },
  { en: "aspect", ko: "측면", pos: "n.", ex: "Consider every aspect of the plan." },
  { en: "assemble", ko: "조립하다, 모으다", pos: "v.", ex: "We need to assemble the furniture." },
  { en: "assert", ko: "주장하다", pos: "v.", ex: "He asserted that he was innocent." },
  { en: "assess", ko: "평가하다", pos: "v.", ex: "Teachers assess students' progress regularly." },
  { en: "assume", ko: "가정하다", pos: "v.", ex: "Don't assume he already knows." },
  { en: "assure", ko: "확언하다, 안심시키다", pos: "v.", ex: "I assure you everything is fine." },
  { en: "attain", ko: "달성하다", pos: "v.", ex: "She attained her degree in three years." },
  { en: "attribute", ko: "~탓으로 하다, 속성", pos: "v./n.", ex: "He attributed his success to hard work." },
  { en: "authentic", ko: "진짜의, 진정한", pos: "adj.", ex: "This is an authentic Italian recipe." },
  { en: "available", ko: "이용 가능한", pos: "adj.", ex: "The tickets are no longer available." },
  { en: "aware", ko: "알고 있는", pos: "adj.", ex: "Are you aware of the new rules?" },
  { en: "beneficial", ko: "유익한", pos: "adj.", ex: "Exercise is beneficial for your health." },
  { en: "bias", ko: "편견", pos: "n.", ex: "The report showed clear bias." },
  { en: "boost", ko: "북돋우다, 증가시키다", pos: "v.", ex: "The news boosted the company's stock." },
  { en: "brief", ko: "간단한, 짧은", pos: "adj.", ex: "Please keep your answer brief." },
  { en: "capable", ko: "~할 수 있는", pos: "adj.", ex: "She is capable of great things." },
  { en: "capacity", ko: "용량, 능력", pos: "n.", ex: "The stadium has a huge capacity." },
  { en: "cease", ko: "중단하다", pos: "v.", ex: "The factory ceased operations last year." },
  { en: "circumstance", ko: "상황, 환경", pos: "n.", ex: "Under no circumstance should you leave." },
  { en: "clarify", ko: "명확히 하다", pos: "v.", ex: "Could you clarify what you mean?" },
  { en: "coherent", ko: "일관성 있는", pos: "adj.", ex: "His argument was clear and coherent." },
  { en: "collapse", ko: "붕괴하다", pos: "v.", ex: "The old bridge finally collapsed." },
  { en: "comprehend", ko: "이해하다", pos: "v.", ex: "It's hard to comprehend such loss." },
  { en: "conceal", ko: "숨기다", pos: "v.", ex: "She tried to conceal her feelings." },
  { en: "concise", ko: "간결한", pos: "adj.", ex: "Write a concise summary of the report." },
  { en: "conclude", ko: "결론짓다", pos: "v.", ex: "We conclude that the plan works." },
  { en: "confront", ko: "직면하다, 맞서다", pos: "v.", ex: "He decided to confront the problem." },
  { en: "consequence", ko: "결과", pos: "n.", ex: "Every choice has a consequence." },
  { en: "considerable", ko: "상당한", pos: "adj.", ex: "They spent a considerable amount of money." },
  { en: "consistent", ko: "일관된", pos: "adj.", ex: "Her performance has been consistent." },
  { en: "constrain", ko: "제약하다", pos: "v.", ex: "Budget cuts constrain our options." },
  { en: "contemplate", ko: "숙고하다", pos: "v.", ex: "He contemplated quitting his job." },
  { en: "contradict", ko: "모순되다, 반박하다", pos: "v.", ex: "The two reports contradict each other." },
  { en: "contribute", ko: "기여하다", pos: "v.", ex: "Everyone contributed to the project." },
  { en: "controversial", ko: "논란이 많은", pos: "adj.", ex: "It was a controversial decision." },
  { en: "convince", ko: "설득하다", pos: "v.", ex: "She convinced him to stay." },
  { en: "cooperate", ko: "협력하다", pos: "v.", ex: "The teams agreed to cooperate." },
  { en: "coordinate", ko: "조정하다", pos: "v.", ex: "She coordinates the event schedule." },
  { en: "crucial", ko: "중요한, 결정적인", pos: "adj.", ex: "This decision is crucial for us." },
  { en: "cumulative", ko: "누적되는", pos: "adj.", ex: "The effect is cumulative over years." },
  { en: "curious", ko: "호기심 있는", pos: "adj.", ex: "The child was curious about everything." },
  { en: "decline", ko: "감소하다, 거절하다", pos: "v./n.", ex: "Sales declined sharply last month." },
  { en: "deficient", ko: "부족한", pos: "adj.", ex: "The diet was deficient in vitamins." },
  { en: "define", ko: "정의하다", pos: "v.", ex: "Let's define our goals clearly." },
  { en: "demonstrate", ko: "증명하다, 시연하다", pos: "v.", ex: "The study demonstrates a clear link." },
  { en: "deny", ko: "부인하다", pos: "v.", ex: "He denied any involvement." },
  { en: "derive", ko: "유래하다, 얻다", pos: "v.", ex: "The word derives from Latin." },
  { en: "designate", ko: "지정하다", pos: "v.", ex: "This area is designated for parking." },
  { en: "despite", ko: "~에도 불구하고", pos: "prep.", ex: "Despite the rain, they went out." },
  { en: "deteriorate", ko: "악화되다", pos: "v.", ex: "His health began to deteriorate." },
  { en: "devote", ko: "바치다, 헌신하다", pos: "v.", ex: "She devotes her time to charity." },
  { en: "diminish", ko: "줄어들다", pos: "v.", ex: "His enthusiasm began to diminish." },
  { en: "discrepancy", ko: "차이, 불일치", pos: "n.", ex: "There is a discrepancy in the report." },
  { en: "distinct", ko: "뚜렷한, 별개의", pos: "adj.", ex: "The two ideas are quite distinct." },
  { en: "distribute", ko: "분배하다", pos: "v.", ex: "Volunteers distributed food to the poor." },
  { en: "diverse", ko: "다양한", pos: "adj.", ex: "The city has a diverse population." },
  { en: "domestic", ko: "국내의, 가정의", pos: "adj.", ex: "The company focuses on domestic sales." },
  { en: "dominant", ko: "지배적인", pos: "adj.", ex: "English is the dominant language here." },
  { en: "durable", ko: "내구성 있는", pos: "adj.", ex: "These shoes are very durable." },
  { en: "eliminate", ko: "제거하다", pos: "v.", ex: "We need to eliminate the errors." },
  { en: "emerge", ko: "나타나다, 부상하다", pos: "v.", ex: "A new leader began to emerge." },
  { en: "emphasize", ko: "강조하다", pos: "v.", ex: "The teacher emphasized safety rules." },
  { en: "enhance", ko: "향상시키다", pos: "v.", ex: "The update will enhance performance." },
  { en: "enormous", ko: "거대한", pos: "adj.", ex: "They built an enormous new stadium." },
  { en: "ensure", ko: "보장하다", pos: "v.", ex: "Please ensure the door is locked." },
  { en: "equivalent", ko: "동등한", pos: "adj.", ex: "One mile is equivalent to 1.6 km." },
  { en: "essential", ko: "필수적인", pos: "adj.", ex: "Water is essential for life." },
  { en: "establish", ko: "설립하다, 확립하다", pos: "v.", ex: "The company was established in 1990." },
  { en: "estimate", ko: "추정하다", pos: "v./n.", ex: "We estimate the cost at $500." },
  { en: "evaluate", ko: "평가하다", pos: "v.", ex: "Please evaluate this proposal carefully." },
  { en: "eventually", ko: "결국", pos: "adv.", ex: "Eventually, she found the right job." },
  { en: "evident", ko: "명백한", pos: "adj.", ex: "It was evident that he was upset." },
  { en: "evoke", ko: "불러일으키다", pos: "v.", ex: "The song evokes fond memories." },
  { en: "exceed", ko: "초과하다", pos: "v.", ex: "Do not exceed the speed limit." },
  { en: "exhibit", ko: "전시하다, 보이다", pos: "v.", ex: "The museum exhibits ancient artifacts." },
  { en: "expand", ko: "확장하다", pos: "v.", ex: "The company plans to expand overseas." },
  { en: "explicit", ko: "명확한, 명시적인", pos: "adj.", ex: "He gave explicit instructions." },
  { en: "exploit", ko: "이용하다, 착취하다", pos: "v.", ex: "They exploited the natural resources." },
  { en: "extract", ko: "추출하다", pos: "v.", ex: "Machines extract oil from the seeds." },
  { en: "facilitate", ko: "촉진하다, 용이하게 하다", pos: "v.", ex: "The app facilitates quick payments." },
  { en: "feasible", ko: "실현 가능한", pos: "adj.", ex: "Is this plan financially feasible?" },
  { en: "fluctuate", ko: "변동하다", pos: "v.", ex: "Prices fluctuate throughout the year." },
  { en: "fundamental", ko: "근본적인", pos: "adj.", ex: "Trust is fundamental to any team." },
  { en: "generate", ko: "생성하다", pos: "v.", ex: "Solar panels generate electricity." },
  { en: "genuine", ko: "진실한, 진짜의", pos: "adj.", ex: "She showed genuine concern for us." },
  { en: "gradual", ko: "점진적인", pos: "adj.", ex: "There was a gradual improvement." },
  { en: "hesitate", ko: "망설이다", pos: "v.", ex: "Don't hesitate to ask questions." },
  { en: "hypothesis", ko: "가설", pos: "n.", ex: "The scientist tested her hypothesis." },
  { en: "identical", ko: "동일한", pos: "adj.", ex: "The twins looked identical." },
  { en: "illustrate", ko: "설명하다, 예시하다", pos: "v.", ex: "This chart illustrates the trend." },
  { en: "immense", ko: "엄청난", pos: "adj.", ex: "The project required immense effort." },
  { en: "implement", ko: "시행하다", pos: "v.", ex: "The school will implement new rules." },
  { en: "imply", ko: "암시하다", pos: "v.", ex: "Her silence implied disagreement." },
  { en: "impose", ko: "부과하다, 강요하다", pos: "v.", ex: "The government imposed a new tax." },
  { en: "incentive", ko: "동기, 유인책", pos: "n.", ex: "The bonus is a strong incentive." },
  { en: "inevitable", ko: "불가피한", pos: "adj.", ex: "Change is inevitable in life." },
  { en: "infer", ko: "추론하다", pos: "v.", ex: "We can infer his intent from this." },
  { en: "innovative", ko: "혁신적인", pos: "adj.", ex: "It's a very innovative design." },
  { en: "instance", ko: "예, 사례", pos: "n.", ex: "For instance, consider this example." },
  { en: "integrate", ko: "통합하다", pos: "v.", ex: "We need to integrate the two systems." },
  { en: "intense", ko: "강렬한, 극심한", pos: "adj.", ex: "The heat was intense that day." },
  { en: "interpret", ko: "해석하다", pos: "v.", ex: "How do you interpret this data?" },
  { en: "intervene", ko: "개입하다", pos: "v.", ex: "The teacher intervened in the fight." },
  { en: "intuitive", ko: "직관적인", pos: "adj.", ex: "The app has an intuitive interface." },
  { en: "invoke", ko: "불러일으키다, 발동하다", pos: "v.", ex: "The law was invoked immediately." },
  { en: "isolate", ko: "고립시키다", pos: "v.", ex: "The patient was isolated for safety." },
  { en: "justify", ko: "정당화하다", pos: "v.", ex: "Can you justify this expense?" },
  { en: "legitimate", ko: "합법적인, 정당한", pos: "adj.", ex: "It's a legitimate business concern." },
  { en: "leverage", ko: "활용하다, 지렛대", pos: "v./n.", ex: "We should leverage our strengths." },
  { en: "manipulate", ko: "조작하다", pos: "v.", ex: "He tried to manipulate the results." },
  { en: "mediate", ko: "중재하다", pos: "v.", ex: "A lawyer mediated the dispute." },
  { en: "mere", ko: "단순한, ~에 불과한", pos: "adj.", ex: "It was a mere coincidence." },
  { en: "minimal", ko: "최소한의", pos: "adj.", ex: "The damage was minimal." },
  { en: "mitigate", ko: "완화하다", pos: "v.", ex: "The plan aims to mitigate risks." },
  { en: "modify", ko: "수정하다", pos: "v.", ex: "We need to modify the design." },
  { en: "negotiate", ko: "협상하다", pos: "v.", ex: "They negotiated a better price." },
  { en: "notion", ko: "개념, 생각", pos: "n.", ex: "That's a strange notion to me." },
  { en: "notable", ko: "주목할 만한", pos: "adj.", ex: "There were several notable exceptions." },
  { en: "obvious", ko: "명백한", pos: "adj.", ex: "The answer seemed obvious to her." },
  { en: "occupy", ko: "차지하다, 점유하다", pos: "v.", ex: "The army occupied the region." },
  { en: "obstacle", ko: "장애물", pos: "n.", ex: "Fear can be a big obstacle." },
  { en: "outcome", ko: "결과", pos: "n.", ex: "We are happy with the outcome." },
  { en: "overwhelm", ko: "압도하다", pos: "v.", ex: "She felt overwhelmed by the news." },
  { en: "perceive", ko: "인지하다", pos: "v.", ex: "People perceive risk differently." },
  { en: "persist", ko: "지속하다, 끈기 있게 하다", pos: "v.", ex: "The rain persisted all week." },
  { en: "phenomenon", ko: "현상", pos: "n.", ex: "It's a common social phenomenon." },
  { en: "plausible", ko: "그럴듯한", pos: "adj.", ex: "That's a plausible explanation." },
  { en: "potential", ko: "잠재력, 가능성 있는", pos: "n./adj.", ex: "She has great potential as a leader." },
  { en: "practical", ko: "실용적인", pos: "adj.", ex: "We need a practical solution." },
  { en: "precede", ko: "선행하다", pos: "v.", ex: "A warning light precedes the alarm." },
  { en: "predominant", ko: "지배적인, 우세한", pos: "adj.", ex: "Blue is the predominant color here." },
  { en: "preliminary", ko: "예비의", pos: "adj.", ex: "These are only preliminary results." },
  { en: "presume", ko: "추정하다", pos: "v.", ex: "I presume you already know this." },
  { en: "prevail", ko: "만연하다, 우세하다", pos: "v.", ex: "Justice will eventually prevail." },
  { en: "previous", ko: "이전의", pos: "adj.", ex: "In the previous chapter, we saw this." },
  { en: "primary", ko: "주요한, 최초의", pos: "adj.", ex: "Our primary goal is safety." },
  { en: "prior", ko: "이전의, 사전의", pos: "adj.", ex: "You need prior approval to enter." },
  { en: "proceed", ko: "진행하다", pos: "v.", ex: "Let's proceed with the plan." },
  { en: "profound", ko: "깊은, 심오한", pos: "adj.", ex: "The book had a profound impact." },
  { en: "prohibit", ko: "금지하다", pos: "v.", ex: "Smoking is prohibited indoors." },
  { en: "prominent", ko: "저명한, 두드러진", pos: "adj.", ex: "He is a prominent scientist." },
  { en: "prospect", ko: "전망, 가능성", pos: "n.", ex: "The job offers good prospects." },
  { en: "provoke", ko: "유발하다, 자극하다", pos: "v.", ex: "The remark provoked strong reactions." },
  { en: "pursue", ko: "추구하다", pos: "v.", ex: "She decided to pursue a new career." },
  { en: "rational", ko: "합리적인", pos: "adj.", ex: "Try to make a rational decision." },
  { en: "reinforce", ko: "강화하다", pos: "v.", ex: "The steel bars reinforce the wall." },
  { en: "reluctant", ko: "꺼리는, 마지못한", pos: "adj.", ex: "He was reluctant to speak up." },
  { en: "resemble", ko: "닮다", pos: "v.", ex: "She resembles her grandmother a lot." },
  { en: "resolve", ko: "해결하다, 결심하다", pos: "v.", ex: "They resolved the conflict peacefully." },
  { en: "restrain", ko: "억제하다", pos: "v.", ex: "He restrained his anger." },
  { en: "reveal", ko: "드러내다", pos: "v.", ex: "The report reveals hidden costs." },
  { en: "rigid", ko: "엄격한, 경직된", pos: "adj.", ex: "The rules here are quite rigid." },
  { en: "scarce", ko: "부족한, 희귀한", pos: "adj.", ex: "Clean water is scarce in the region." },
  { en: "significant", ko: "중요한, 상당한", pos: "adj.", ex: "There was a significant change." },
  { en: "simultaneous", ko: "동시의", pos: "adj.", ex: "The two events were simultaneous." },
  { en: "sophisticated", ko: "정교한, 세련된", pos: "adj.", ex: "It's a very sophisticated system." },
  { en: "spontaneous", ko: "자발적인", pos: "adj.", ex: "It was a spontaneous decision." },
  { en: "subsequent", ko: "그 다음의, 후속의", pos: "adj.", ex: "Subsequent events proved him right." },
  { en: "substantial", ko: "상당한, 실질적인", pos: "adj.", ex: "They made substantial progress." },
  { en: "sufficient", ko: "충분한", pos: "adj.", ex: "We have sufficient evidence now." },
  { en: "suppress", ko: "억압하다, 억누르다", pos: "v.", ex: "She tried to suppress a smile." },
  { en: "sustain", ko: "지속하다, 유지하다", pos: "v.", ex: "The economy sustained steady growth." },
  { en: "tentative", ko: "잠정적인", pos: "adj.", ex: "We made a tentative agreement." },
  { en: "thorough", ko: "철저한", pos: "adj.", ex: "She did a thorough investigation." },
  { en: "transform", ko: "변형시키다", pos: "v.", ex: "The city was transformed overnight." },
  { en: "trigger", ko: "촉발시키다, 방아쇠", pos: "v./n.", ex: "The comment triggered a debate." },
  { en: "ultimate", ko: "궁극적인, 최종적인", pos: "adj.", ex: "Our ultimate goal is world peace." },
  { en: "undermine", ko: "약화시키다", pos: "v.", ex: "Doubt can undermine confidence." },
  { en: "unprecedented", ko: "전례 없는", pos: "adj.", ex: "It was an unprecedented crisis." },
  { en: "utilize", ko: "활용하다", pos: "v.", ex: "We should utilize all resources." },
  { en: "vague", ko: "모호한", pos: "adj.", ex: "His answer was vague and unclear." },
  { en: "verify", ko: "검증하다", pos: "v.", ex: "Please verify your email address." },
  { en: "vigorous", ko: "활발한, 격렬한", pos: "adj.", ex: "She gave a vigorous defense." },
  { en: "virtually", ko: "사실상, 거의", pos: "adv.", ex: "The task is virtually impossible." },
  { en: "vivid", ko: "생생한", pos: "adj.", ex: "He gave a vivid description." },
  { en: "volatile", ko: "변동이 심한, 불안정한", pos: "adj.", ex: "The stock market is volatile now." },
  { en: "widespread", ko: "널리 퍼진", pos: "adj.", ex: "There is widespread support for the plan." },
];

if (typeof module !== "undefined") {
  module.exports = WORD_BANK;
}
